// Code generated by tsgo-generate; DO NOT EDIT.
//
// Grammar: json
// Symbols: 25, States: 32 (7 large, 25 small)
package testgrammars

import (
	core "github.com/treesitter-go/treesitter/internal/core"
	language "github.com/treesitter-go/treesitter/language"
	lex "github.com/treesitter-go/treesitter/lexer"
)

// Grammar symbol IDs.
const (
	SymEnd              core.Symbol = 0
	SymLBrace           core.Symbol = 1
	SymComma            core.Symbol = 2
	SymRBrace           core.Symbol = 3
	SymColon            core.Symbol = 4
	SymLBrack           core.Symbol = 5
	SymRBrack           core.Symbol = 6
	SymDQuote           core.Symbol = 7
	SymStringContent    core.Symbol = 8
	SymEscapeSequence   core.Symbol = 9
	SymNumber           core.Symbol = 10
	SymTrue             core.Symbol = 11
	SymFalse            core.Symbol = 12
	SymNull             core.Symbol = 13
	SymComment          core.Symbol = 14
	SymDocument         core.Symbol = 15
	SymAuxValue         core.Symbol = 16
	SymObject           core.Symbol = 17
	SymPair             core.Symbol = 18
	SymArray            core.Symbol = 19
	SymString           core.Symbol = 20
	SymAuxStringContent core.Symbol = 21
	SymDocumentRepeat1  core.Symbol = 22
	SymObjectRepeat1    core.Symbol = 23
	SymArrayRepeat1     core.Symbol = 24
)

// Grammar field IDs.
const (
	FieldKey   core.FieldID = 1
	FieldValue core.FieldID = 2
)

// JsonLanguage returns the compiled json grammar as a Language.
func JsonLanguage() *language.Language {
	parseActions := []core.ParseActionEntry{
		// [0]
		{Type: core.ParseActionTypeHeader, Count: 0, Reusable: false},
		// [1]
		{Type: core.ParseActionTypeHeader, Count: 1, Reusable: false},
		{Type: core.ParseActionTypeRecover},
		// [3]
		{Type: core.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: core.ParseActionTypeShift, ShiftExtra: true},
		// [5]
		{Type: core.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: core.ParseActionTypeReduce, ReduceSymbol: 15, ReduceChildCount: 0},
		// [7]
		{Type: core.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: core.ParseActionTypeShift, ShiftState: 16},
		// [9]
		{Type: core.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: core.ParseActionTypeShift, ShiftState: 4},
		// [11]
		{Type: core.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: core.ParseActionTypeShift, ShiftState: 17},
		// [13]
		{Type: core.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: core.ParseActionTypeShift, ShiftState: 8},
		// [15]
		{Type: core.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: core.ParseActionTypeReduce, ReduceSymbol: 15, ReduceChildCount: 1},
		// [17]
		{Type: core.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: core.ParseActionTypeReduce, ReduceSymbol: 22, ReduceChildCount: 2},
		// [19]
		{Type: core.ParseActionTypeHeader, Count: 2, Reusable: true},
		{Type: core.ParseActionTypeReduce, ReduceSymbol: 22, ReduceChildCount: 2},
		{Type: core.ParseActionTypeShift, ShiftState: 16, ShiftRepetition: true},
		// [22]
		{Type: core.ParseActionTypeHeader, Count: 2, Reusable: true},
		{Type: core.ParseActionTypeReduce, ReduceSymbol: 22, ReduceChildCount: 2},
		{Type: core.ParseActionTypeShift, ShiftState: 4, ShiftRepetition: true},
		// [25]
		{Type: core.ParseActionTypeHeader, Count: 2, Reusable: true},
		{Type: core.ParseActionTypeReduce, ReduceSymbol: 22, ReduceChildCount: 2},
		{Type: core.ParseActionTypeShift, ShiftState: 17, ShiftRepetition: true},
		// [28]
		{Type: core.ParseActionTypeHeader, Count: 2, Reusable: true},
		{Type: core.ParseActionTypeReduce, ReduceSymbol: 22, ReduceChildCount: 2},
		{Type: core.ParseActionTypeShift, ShiftState: 8, ShiftRepetition: true},
		// [31]
		{Type: core.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: core.ParseActionTypeShift, ShiftState: 9},
		// [33]
		{Type: core.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: core.ParseActionTypeReduce, ReduceSymbol: 20, ReduceChildCount: 2},
		// [35]
		{Type: core.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: core.ParseActionTypeReduce, ReduceSymbol: 20, ReduceChildCount: 3},
		// [37]
		{Type: core.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: core.ParseActionTypeReduce, ReduceSymbol: 17, ReduceChildCount: 2},
		// [39]
		{Type: core.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: core.ParseActionTypeReduce, ReduceSymbol: 16, ReduceChildCount: 1},
		// [41]
		{Type: core.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: core.ParseActionTypeReduce, ReduceSymbol: 19, ReduceChildCount: 2},
		// [43]
		{Type: core.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: core.ParseActionTypeReduce, ReduceSymbol: 17, ReduceChildCount: 3},
		// [45]
		{Type: core.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: core.ParseActionTypeReduce, ReduceSymbol: 17, ReduceChildCount: 4},
		// [47]
		{Type: core.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: core.ParseActionTypeReduce, ReduceSymbol: 19, ReduceChildCount: 3},
		// [49]
		{Type: core.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: core.ParseActionTypeReduce, ReduceSymbol: 19, ReduceChildCount: 4},
		// [51]
		{Type: core.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: core.ParseActionTypeShift, ShiftState: 7},
		// [53]
		{Type: core.ParseActionTypeHeader, Count: 1, Reusable: false},
		{Type: core.ParseActionTypeShift, ShiftState: 5},
		// [55]
		{Type: core.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: core.ParseActionTypeShift, ShiftState: 18},
		// [57]
		{Type: core.ParseActionTypeHeader, Count: 1, Reusable: false},
		{Type: core.ParseActionTypeShift, ShiftExtra: true},
		// [59]
		{Type: core.ParseActionTypeHeader, Count: 1, Reusable: false},
		{Type: core.ParseActionTypeShift, ShiftState: 6},
		// [61]
		{Type: core.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: core.ParseActionTypeShift, ShiftState: 19},
		// [63]
		{Type: core.ParseActionTypeHeader, Count: 1, Reusable: false},
		{Type: core.ParseActionTypeReduce, ReduceSymbol: 21, ReduceChildCount: 2},
		// [65]
		{Type: core.ParseActionTypeHeader, Count: 2, Reusable: true},
		{Type: core.ParseActionTypeReduce, ReduceSymbol: 21, ReduceChildCount: 2},
		{Type: core.ParseActionTypeShift, ShiftState: 19, ShiftRepetition: true},
		// [68]
		{Type: core.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: core.ParseActionTypeShift, ShiftState: 23},
		// [70]
		{Type: core.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: core.ParseActionTypeShift, ShiftState: 11},
		// [72]
		{Type: core.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: core.ParseActionTypeShift, ShiftState: 10},
		// [74]
		{Type: core.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: core.ParseActionTypeShift, ShiftState: 14},
		// [76]
		{Type: core.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: core.ParseActionTypeShift, ShiftState: 12},
		// [78]
		{Type: core.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: core.ParseActionTypeShift, ShiftState: 15},
		// [80]
		{Type: core.ParseActionTypeHeader, Count: 2, Reusable: true},
		{Type: core.ParseActionTypeReduce, ReduceSymbol: 23, ReduceChildCount: 2},
		{Type: core.ParseActionTypeShift, ShiftState: 23, ShiftRepetition: true},
		// [83]
		{Type: core.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: core.ParseActionTypeReduce, ReduceSymbol: 23, ReduceChildCount: 2},
		// [85]
		{Type: core.ParseActionTypeHeader, Count: 2, Reusable: true},
		{Type: core.ParseActionTypeReduce, ReduceSymbol: 24, ReduceChildCount: 2},
		{Type: core.ParseActionTypeShift, ShiftState: 10, ShiftRepetition: true},
		// [88]
		{Type: core.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: core.ParseActionTypeReduce, ReduceSymbol: 24, ReduceChildCount: 2},
		// [90]
		{Type: core.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: core.ParseActionTypeReduce, ReduceSymbol: 18, ReduceChildCount: 3, ReduceProdID: 1},
		// [92]
		{Type: core.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: core.ParseActionTypeAccept},
		// [94]
		{Type: core.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: core.ParseActionTypeShift, ShiftState: 13},
	}

	parseTable := []uint16{
		// State 0
		1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
		// State 1
		5, 7, 0, 0, 0, 9, 0, 11, 0, 0, 13, 13, 13, 13, 3, 30, 2, 8, 0, 8, 8, 0, 2, 0, 0,
		// State 2
		15, 7, 0, 0, 0, 9, 0, 11, 0, 0, 13, 13, 13, 13, 3, 0, 3, 8, 0, 8, 8, 0, 3, 0, 0,
		// State 3
		17, 19, 0, 0, 0, 22, 0, 25, 0, 0, 28, 28, 28, 28, 3, 0, 3, 8, 0, 8, 8, 0, 3, 0, 0,
		// State 4
		0, 7, 0, 0, 0, 9, 31, 11, 0, 0, 13, 13, 13, 13, 3, 0, 21, 8, 0, 8, 8, 0, 0, 0, 0,
		// State 5
		33, 33, 33, 33, 33, 33, 33, 33, 0, 0, 33, 33, 33, 33, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
		// State 6
		35, 35, 35, 35, 35, 35, 35, 35, 0, 0, 35, 35, 35, 35, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	}

	smallParseTable := []uint16{
		2, 3, 1, 14, 37, 11, 0, 1, 2, 3, 5, 6, 7, 10, 11, 12, 13, 2, 3, 1,
		14, 39, 11, 0, 1, 2, 3, 5, 6, 7, 10, 11, 12, 13, 2, 3, 1, 14, 41, 11,
		0, 1, 2, 3, 5, 6, 7, 10, 11, 12, 13, 7, 3, 1, 14, 7, 1, 1, 9, 1,
		5, 11, 1, 7, 29, 1, 16, 8, 3, 17, 19, 20, 13, 4, 10, 11, 12, 13, 2, 3,
		1, 14, 43, 11, 0, 1, 2, 3, 5, 6, 7, 10, 11, 12, 13, 2, 3, 1, 14, 45,
		11, 0, 1, 2, 3, 5, 6, 7, 10, 11, 12, 13, 7, 3, 1, 14, 7, 1, 1, 9,
		1, 5, 11, 1, 7, 28, 1, 16, 8, 3, 17, 19, 20, 13, 4, 10, 11, 12, 13, 2,
		3, 1, 14, 47, 11, 0, 1, 2, 3, 5, 6, 7, 10, 11, 12, 13, 2, 3, 1, 14,
		49, 11, 0, 1, 2, 3, 5, 6, 7, 10, 11, 12, 13, 5, 3, 1, 14, 11, 1, 7,
		51, 1, 3, 20, 1, 18, 31, 1, 20, 4, 53, 1, 7, 57, 1, 14, 18, 1, 21, 55,
		2, 8, 9, 4, 57, 1, 14, 59, 1, 7, 19, 1, 21, 61, 2, 8, 9, 4, 57, 1,
		14, 63, 1, 7, 19, 1, 21, 65, 2, 8, 9, 4, 3, 1, 14, 68, 1, 2, 70, 1,
		3, 22, 1, 23, 4, 3, 1, 14, 72, 1, 2, 74, 1, 6, 24, 1, 24, 4, 3, 1,
		14, 68, 1, 2, 76, 1, 3, 25, 1, 23, 4, 3, 1, 14, 11, 1, 7, 27, 1, 18,
		31, 1, 20, 4, 3, 1, 14, 72, 1, 2, 78, 1, 6, 26, 1, 24, 4, 3, 1, 14,
		80, 1, 2, 83, 1, 3, 25, 1, 23, 4, 3, 1, 14, 85, 1, 2, 88, 1, 6, 26,
		1, 24, 2, 3, 1, 14, 83, 2, 2, 3, 2, 3, 1, 14, 90, 2, 2, 3, 2, 3,
		1, 14, 88, 2, 2, 6, 2, 3, 1, 14, 92, 1, 0, 2, 3, 1, 14, 94, 1, 4,
	}

	smallParseTableMap := []uint32{
		0, 17, 34, 51, 78, 95, 112, 139, 156, 173,
		189, 203, 217, 231, 244, 257, 270, 283, 296, 309,
		322, 330, 338, 346, 353,
	}

	lexModes := []core.LexMode{
		{LexState: 0}, // state 0
		{LexState: 0}, // state 1
		{LexState: 0}, // state 2
		{LexState: 0}, // state 3
		{LexState: 0}, // state 4
		{LexState: 0}, // state 5
		{LexState: 0}, // state 6
		{LexState: 0}, // state 7
		{LexState: 0}, // state 8
		{LexState: 0}, // state 9
		{LexState: 0}, // state 10
		{LexState: 0}, // state 11
		{LexState: 0}, // state 12
		{LexState: 0}, // state 13
		{LexState: 0}, // state 14
		{LexState: 0}, // state 15
		{LexState: 0}, // state 16
		{LexState: 1}, // state 17
		{LexState: 1}, // state 18
		{LexState: 1}, // state 19
		{LexState: 0}, // state 20
		{LexState: 0}, // state 21
		{LexState: 0}, // state 22
		{LexState: 0}, // state 23
		{LexState: 0}, // state 24
		{LexState: 0}, // state 25
		{LexState: 0}, // state 26
		{LexState: 0}, // state 27
		{LexState: 0}, // state 28
		{LexState: 0}, // state 29
		{LexState: 0}, // state 30
		{LexState: 0}, // state 31
	}

	primaryStateIDs := []core.StateID{
		0, 1, 2, 3, 4, 5, 6, 7, 8, 9,
		10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
		20, 21, 22, 23, 24, 25, 26, 27, 28, 29,
		30, 31,
	}

	aliasSequences := make([]core.Symbol, 8)
	_ = aliasSequences

	symbolMetadata := []core.SymbolMetadata{
		{Visible: false, Named: true},                  // 0: end
		{Visible: true, Named: false},                  // 1: {
		{Visible: true, Named: false},                  // 2: ,
		{Visible: true, Named: false},                  // 3: }
		{Visible: true, Named: false},                  // 4: :
		{Visible: true, Named: false},                  // 5: [
		{Visible: true, Named: false},                  // 6: ]
		{Visible: true, Named: false},                  // 7: "
		{Visible: true, Named: true},                   // 8: string_content
		{Visible: true, Named: true},                   // 9: escape_sequence
		{Visible: true, Named: true},                   // 10: number
		{Visible: true, Named: true},                   // 11: true
		{Visible: true, Named: true},                   // 12: false
		{Visible: true, Named: true},                   // 13: null
		{Visible: true, Named: true},                   // 14: comment
		{Visible: true, Named: true},                   // 15: document
		{Visible: false, Named: true, Supertype: true}, // 16: _value
		{Visible: true, Named: true},                   // 17: object
		{Visible: true, Named: true},                   // 18: pair
		{Visible: true, Named: true},                   // 19: array
		{Visible: true, Named: true},                   // 20: string
		{Visible: false, Named: false},                 // 21: _string_content
		{Visible: false, Named: false},                 // 22: document_repeat1
		{Visible: false, Named: false},                 // 23: object_repeat1
		{Visible: false, Named: false},                 // 24: array_repeat1
	}

	symbolNames := []string{
		"end",              // 0
		"{",                // 1
		",",                // 2
		"}",                // 3
		":",                // 4
		"[",                // 5
		"]",                // 6
		"\"",               // 7
		"string_content",   // 8
		"escape_sequence",  // 9
		"number",           // 10
		"true",             // 11
		"false",            // 12
		"null",             // 13
		"comment",          // 14
		"document",         // 15
		"_value",           // 16
		"object",           // 17
		"pair",             // 18
		"array",            // 19
		"string",           // 20
		"_string_content",  // 21
		"document_repeat1", // 22
		"object_repeat1",   // 23
		"array_repeat1",    // 24
	}

	fieldMapSlices := []core.FieldMapSlice{
		{Index: 0, Length: 0},
		{Index: 0, Length: 2},
	}

	fieldMapEntries := []core.FieldMapEntry{
		{FieldID: 1, ChildIndex: 0},
		{FieldID: 2, ChildIndex: 2},
	}

	fieldNames := []string{
		"",
		"key",
		"value",
	}

	supertypeSymbols := []core.Symbol{16}

	publicSymbolMap := []core.Symbol{
		0, 1, 2, 3, 4, 5, 6, 7, 8, 9,
		10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
		20, 21, 22, 23, 24,
	}

	nonTerminalAliasMap := []uint16{
		0,
	}

	return &language.Language{
		Version:                14,
		SymbolCount:            25,
		AliasCount:             0,
		TokenCount:             15,
		ExternalTokenCount:     0,
		StateCount:             32,
		LargeStateCount:        7,
		ProductionIDCount:      2,
		FieldCount:             2,
		MaxAliasSequenceLength: 4,
		PrimaryStateIDs:        primaryStateIDs,
		ParseTable:             parseTable,
		SmallParseTable:        smallParseTable,
		SmallParseTableMap:     smallParseTableMap,
		ParseActions:           parseActions,
		LexModes:               lexModes,
		LexFn:                  tsLex,
		SymbolNames:            symbolNames,
		SymbolMetadata:         symbolMetadata,
		FieldMapSlices:         fieldMapSlices,
		FieldMapEntries:        fieldMapEntries,
		FieldNames:             fieldNames,
		AliasSequences:         aliasSequences,
		SupertypeSymbols:       supertypeSymbols,
		PublicSymbolMap:        publicSymbolMap,
		NonTerminalAliasMap:    nonTerminalAliasMap,
	}
}

func tsLex(lexer *lex.Lexer, state core.StateID) bool {
	result := false
	lookahead := lexer.Lookahead
	eof := lexer.EOF()
	_ = eof

	for {
		switch state {
		case 0:
			if eof {
				state = 21
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead == '"' {
				state = 28
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead == ',' {
				state = 23
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead == '-' {
				state = 7
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead == '/' {
				state = 3
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead == '0' {
				state = 35
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead == ':' {
				state = 25
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead == '[' {
				state = 26
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead == '\\' {
				state = 18
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead == ']' {
				state = 27
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead == 'f' {
				state = 8
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead == 'n' {
				state = 17
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead == 't' {
				state = 14
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead == '{' {
				state = 22
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead == '}' {
				state = 24
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= '\t' && lookahead <= '\r' {
				state = 20
				lexer.Advance(true)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead == ' ' {
				state = 20
				lexer.Advance(true)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= '1' && lookahead <= '9' {
				state = 36
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 1:
			if lookahead == '\n' {
				state = 2
				lexer.Advance(true)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead == '"' {
				state = 28
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead == '/' {
				state = 29
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead == '\\' {
				state = 18
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= '\t' && lookahead <= '\r' {
				state = 32
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead == ' ' {
				state = 32
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if !eof {
				state = 33
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 2:
			if lookahead == '"' {
				state = 28
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead == '/' {
				state = 3
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= '\t' && lookahead <= '\r' {
				state = 2
				lexer.Advance(true)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead == ' ' {
				state = 2
				lexer.Advance(true)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 3:
			if lookahead == '*' {
				state = 5
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead == '/' {
				state = 43
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 4:
			if lookahead == '*' {
				state = 4
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead == '/' {
				state = 42
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if !eof {
				state = 5
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 5:
			if lookahead == '*' {
				state = 4
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if !eof {
				state = 5
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 6:
			if lookahead == '-' {
				state = 19
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= '0' && lookahead <= '9' {
				state = 38
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 7:
			if lookahead == '0' {
				state = 35
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= '1' && lookahead <= '9' {
				state = 36
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 8:
			if lookahead == 'a' {
				state = 11
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 9:
			if lookahead == 'e' {
				state = 39
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 10:
			if lookahead == 'e' {
				state = 40
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 11:
			if lookahead == 'l' {
				state = 15
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 12:
			if lookahead == 'l' {
				state = 41
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 13:
			if lookahead == 'l' {
				state = 12
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 14:
			if lookahead == 'r' {
				state = 16
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 15:
			if lookahead == 's' {
				state = 10
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 16:
			if lookahead == 'u' {
				state = 9
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 17:
			if lookahead == 'u' {
				state = 13
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 18:
			if lookahead == '"' {
				state = 34
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead == '/' {
				state = 34
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead == '\\' {
				state = 34
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead == 'b' {
				state = 34
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead == 'f' {
				state = 34
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead == 'n' {
				state = 34
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead == 'r' {
				state = 34
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead == 't' {
				state = 34
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead == 'u' {
				state = 34
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 19:
			if lookahead >= '0' && lookahead <= '9' {
				state = 38
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 20:
			if eof {
				state = 21
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead == '"' {
				state = 28
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead == ',' {
				state = 23
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead == '-' {
				state = 7
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead == '/' {
				state = 3
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead == '0' {
				state = 35
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead == ':' {
				state = 25
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead == '[' {
				state = 26
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead == ']' {
				state = 27
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead == 'f' {
				state = 8
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead == 'n' {
				state = 17
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead == 't' {
				state = 14
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead == '{' {
				state = 22
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead == '}' {
				state = 24
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= '\t' && lookahead <= '\r' {
				state = 20
				lexer.Advance(true)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead == ' ' {
				state = 20
				lexer.Advance(true)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= '1' && lookahead <= '9' {
				state = 36
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 21:
			return result
		case 22:
			lexer.MarkEnd()
			lexer.AcceptToken(1)
			result = true
			return result
		case 23:
			lexer.MarkEnd()
			lexer.AcceptToken(2)
			result = true
			return result
		case 24:
			lexer.MarkEnd()
			lexer.AcceptToken(3)
			result = true
			return result
		case 25:
			lexer.MarkEnd()
			lexer.AcceptToken(4)
			result = true
			return result
		case 26:
			lexer.MarkEnd()
			lexer.AcceptToken(5)
			result = true
			return result
		case 27:
			lexer.MarkEnd()
			lexer.AcceptToken(6)
			result = true
			return result
		case 28:
			lexer.MarkEnd()
			lexer.AcceptToken(7)
			result = true
			return result
		case 29:
			lexer.MarkEnd()
			lexer.AcceptToken(8)
			result = true
			if lookahead == '*' {
				state = 31
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead == '/' {
				state = 33
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if !eof && lookahead != '\n' && lookahead != '"' && lookahead != '\\' {
				state = 33
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 30:
			lexer.MarkEnd()
			lexer.AcceptToken(8)
			result = true
			if lookahead == '*' {
				state = 30
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead == '/' {
				state = 33
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if !eof && lookahead != '\n' && lookahead != '"' && lookahead != '\\' {
				state = 31
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 31:
			lexer.MarkEnd()
			lexer.AcceptToken(8)
			result = true
			if lookahead == '*' {
				state = 30
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if !eof && lookahead != '\n' && lookahead != '"' && lookahead != '\\' {
				state = 31
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 32:
			lexer.MarkEnd()
			lexer.AcceptToken(8)
			result = true
			if lookahead == '/' {
				state = 29
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= '\v' && lookahead <= '\r' {
				state = 32
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead == '\t' {
				state = 32
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead == ' ' {
				state = 32
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if !eof && lookahead != '"' && lookahead != '\\' && (lookahead < '\t' || lookahead > '\r') {
				state = 33
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 33:
			lexer.MarkEnd()
			lexer.AcceptToken(8)
			result = true
			if !eof && lookahead != '\n' && lookahead != '"' && lookahead != '\\' {
				state = 33
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 34:
			lexer.MarkEnd()
			lexer.AcceptToken(9)
			result = true
			return result
		case 35:
			lexer.MarkEnd()
			lexer.AcceptToken(10)
			result = true
			if lookahead == '.' {
				state = 37
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead == 'E' {
				state = 6
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead == 'e' {
				state = 6
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 36:
			lexer.MarkEnd()
			lexer.AcceptToken(10)
			result = true
			if lookahead == '.' {
				state = 37
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead == 'E' {
				state = 6
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead == 'e' {
				state = 6
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= '0' && lookahead <= '9' {
				state = 36
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 37:
			lexer.MarkEnd()
			lexer.AcceptToken(10)
			result = true
			if lookahead == 'E' {
				state = 6
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead == 'e' {
				state = 6
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= '0' && lookahead <= '9' {
				state = 37
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 38:
			lexer.MarkEnd()
			lexer.AcceptToken(10)
			result = true
			if lookahead >= '0' && lookahead <= '9' {
				state = 38
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 39:
			lexer.MarkEnd()
			lexer.AcceptToken(11)
			result = true
			return result
		case 40:
			lexer.MarkEnd()
			lexer.AcceptToken(12)
			result = true
			return result
		case 41:
			lexer.MarkEnd()
			lexer.AcceptToken(13)
			result = true
			return result
		case 42:
			lexer.MarkEnd()
			lexer.AcceptToken(14)
			result = true
			return result
		case 43:
			lexer.MarkEnd()
			lexer.AcceptToken(14)
			result = true
			if !eof && lookahead != '\n' {
				state = 43
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		default:
			return false
		}
	}
}
