// Code generated by extract_json_grammar.py; DO NOT EDIT.
//
// Package testgrammars provides a machine-extracted tree-sitter JSON grammar for
// validating the treesitter-go runtime data structures and lookup algorithms.
//
// This is based on tree-sitter-json (https://github.com/tree-sitter/tree-sitter-json).
// The grammar has 25 symbols, 32 parse states (7 large, 25 small), no external
// scanner, and 2 fields (key, value).
//
// The parse tables here are extracted from the C-generated parser.c. The lex
// functions are stubs -- full lexing will be validated in Phase 2 (Lexer).
package testgrammars

import ts "github.com/treesitter-go/treesitter"

// JSON grammar symbol IDs.
const (
	SymEnd                ts.Symbol = 0  // "end"
	SymLBrace             ts.Symbol = 1  // "{"
	SymComma              ts.Symbol = 2  // ","
	SymRBrace             ts.Symbol = 3  // "}"
	SymColon              ts.Symbol = 4  // ":"
	SymLBrack             ts.Symbol = 5  // "["
	SymRBrack             ts.Symbol = 6  // "]"
	SymDQuote             ts.Symbol = 7  // "\""
	SymStringContent      ts.Symbol = 8  // string_content
	SymEscapeSequence     ts.Symbol = 9  // escape_sequence
	SymNumber             ts.Symbol = 10  // number
	SymTrue               ts.Symbol = 11  // true
	SymFalse              ts.Symbol = 12  // false
	SymNull               ts.Symbol = 13  // null
	SymComment            ts.Symbol = 14  // comment
	SymDocument           ts.Symbol = 15  // document
	SymValue              ts.Symbol = 16  // _value (hidden supertype)
	SymObject             ts.Symbol = 17  // object
	SymPair               ts.Symbol = 18  // pair
	SymArray              ts.Symbol = 19  // array
	SymString             ts.Symbol = 20  // string
	SymAuxStringContent   ts.Symbol = 21  // _string_content (aux)
	SymAuxDocumentRepeat1 ts.Symbol = 22  // document_repeat1 (aux)
	SymAuxObjectRepeat1   ts.Symbol = 23  // object_repeat1 (aux)
	SymAuxArrayRepeat1    ts.Symbol = 24  // array_repeat1 (aux)
)

// JSON grammar field IDs.
const (
	FieldKey   ts.FieldID = 1
	FieldValue ts.FieldID = 2
)

// JSONLanguage returns the machine-extracted JSON grammar as a Language.
//
// The parse tables are from tree-sitter-json's generated parser.c.
// Large state parse table: 7 states x 25 symbols (dense 2D array).
// Small state parse table: 25 states in compressed grouped format.
func JSONLanguage() *ts.Language {
	const symbolCount = 25

	// --- Parse actions table ---
	// Each entry at a header position has {count, reusable},
	// followed by `count` action entries.
	parseActions := []ts.ParseActionEntry{
 // [0]: sentinel (no action)
		{Type: ts.ParseActionTypeHeader, Count: 0, Reusable: false},
 // [1]: RECOVER
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: false},
		{Type: ts.ParseActionTypeRecover},
 // [3]: SHIFT_EXTRA
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeShift, ShiftExtra: true},
 // [5]: REDUCE(SymDocument, 0)
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeReduce, ReduceSymbol: SymDocument, ReduceChildCount: 0},
 // [7]: SHIFT(16)
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeShift, ShiftState: 16},
 // [9]: SHIFT(4)
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeShift, ShiftState: 4},
 // [11]: SHIFT(17)
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeShift, ShiftState: 17},
 // [13]: SHIFT(8)
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeShift, ShiftState: 8},
 // [15]: REDUCE(SymDocument, 1)
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeReduce, ReduceSymbol: SymDocument, ReduceChildCount: 1},
 // [17]: REDUCE(SymAuxDocumentRepeat1, 2)
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeReduce, ReduceSymbol: SymAuxDocumentRepeat1, ReduceChildCount: 2},
 // [19]: REDUCE(SymAuxDocumentRepeat1, 2), SHIFT_REPEAT(16)
		{Type: ts.ParseActionTypeHeader, Count: 2, Reusable: true},
		{Type: ts.ParseActionTypeReduce, ReduceSymbol: SymAuxDocumentRepeat1, ReduceChildCount: 2},
		{Type: ts.ParseActionTypeShift, ShiftState: 16, ShiftRepetition: true},
 // [22]: REDUCE(SymAuxDocumentRepeat1, 2), SHIFT_REPEAT(4)
		{Type: ts.ParseActionTypeHeader, Count: 2, Reusable: true},
		{Type: ts.ParseActionTypeReduce, ReduceSymbol: SymAuxDocumentRepeat1, ReduceChildCount: 2},
		{Type: ts.ParseActionTypeShift, ShiftState: 4, ShiftRepetition: true},
 // [25]: REDUCE(SymAuxDocumentRepeat1, 2), SHIFT_REPEAT(17)
		{Type: ts.ParseActionTypeHeader, Count: 2, Reusable: true},
		{Type: ts.ParseActionTypeReduce, ReduceSymbol: SymAuxDocumentRepeat1, ReduceChildCount: 2},
		{Type: ts.ParseActionTypeShift, ShiftState: 17, ShiftRepetition: true},
 // [28]: REDUCE(SymAuxDocumentRepeat1, 2), SHIFT_REPEAT(8)
		{Type: ts.ParseActionTypeHeader, Count: 2, Reusable: true},
		{Type: ts.ParseActionTypeReduce, ReduceSymbol: SymAuxDocumentRepeat1, ReduceChildCount: 2},
		{Type: ts.ParseActionTypeShift, ShiftState: 8, ShiftRepetition: true},
 // [31]: SHIFT(9)
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeShift, ShiftState: 9},
 // [33]: REDUCE(SymString, 2)
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeReduce, ReduceSymbol: SymString, ReduceChildCount: 2},
 // [35]: REDUCE(SymString, 3)
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeReduce, ReduceSymbol: SymString, ReduceChildCount: 3},
 // [37]: REDUCE(SymObject, 2)
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeReduce, ReduceSymbol: SymObject, ReduceChildCount: 2},
 // [39]: REDUCE(SymValue, 1)
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeReduce, ReduceSymbol: SymValue, ReduceChildCount: 1},
 // [41]: REDUCE(SymArray, 2)
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeReduce, ReduceSymbol: SymArray, ReduceChildCount: 2},
 // [43]: REDUCE(SymObject, 3)
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeReduce, ReduceSymbol: SymObject, ReduceChildCount: 3},
 // [45]: REDUCE(SymObject, 4)
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeReduce, ReduceSymbol: SymObject, ReduceChildCount: 4},
 // [47]: REDUCE(SymArray, 3)
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeReduce, ReduceSymbol: SymArray, ReduceChildCount: 3},
 // [49]: REDUCE(SymArray, 4)
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeReduce, ReduceSymbol: SymArray, ReduceChildCount: 4},
 // [51]: SHIFT(7)
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeShift, ShiftState: 7},
 // [53]: SHIFT(5)
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: false},
		{Type: ts.ParseActionTypeShift, ShiftState: 5},
 // [55]: SHIFT(18)
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeShift, ShiftState: 18},
 // [57]: SHIFT_EXTRA
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: false},
		{Type: ts.ParseActionTypeShift, ShiftExtra: true},
 // [59]: SHIFT(6)
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: false},
		{Type: ts.ParseActionTypeShift, ShiftState: 6},
 // [61]: SHIFT(19)
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeShift, ShiftState: 19},
 // [63]: REDUCE(SymAuxStringContent, 2)
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: false},
		{Type: ts.ParseActionTypeReduce, ReduceSymbol: SymAuxStringContent, ReduceChildCount: 2},
 // [65]: REDUCE(SymAuxStringContent, 2), SHIFT_REPEAT(19)
		{Type: ts.ParseActionTypeHeader, Count: 2, Reusable: true},
		{Type: ts.ParseActionTypeReduce, ReduceSymbol: SymAuxStringContent, ReduceChildCount: 2},
		{Type: ts.ParseActionTypeShift, ShiftState: 19, ShiftRepetition: true},
 // [68]: SHIFT(23)
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeShift, ShiftState: 23},
 // [70]: SHIFT(11)
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeShift, ShiftState: 11},
 // [72]: SHIFT(10)
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeShift, ShiftState: 10},
 // [74]: SHIFT(14)
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeShift, ShiftState: 14},
 // [76]: SHIFT(12)
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeShift, ShiftState: 12},
 // [78]: SHIFT(15)
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeShift, ShiftState: 15},
 // [80]: REDUCE(SymAuxObjectRepeat1, 2), SHIFT_REPEAT(23)
		{Type: ts.ParseActionTypeHeader, Count: 2, Reusable: true},
		{Type: ts.ParseActionTypeReduce, ReduceSymbol: SymAuxObjectRepeat1, ReduceChildCount: 2},
		{Type: ts.ParseActionTypeShift, ShiftState: 23, ShiftRepetition: true},
 // [83]: REDUCE(SymAuxObjectRepeat1, 2)
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeReduce, ReduceSymbol: SymAuxObjectRepeat1, ReduceChildCount: 2},
 // [85]: REDUCE(SymAuxArrayRepeat1, 2), SHIFT_REPEAT(10)
		{Type: ts.ParseActionTypeHeader, Count: 2, Reusable: true},
		{Type: ts.ParseActionTypeReduce, ReduceSymbol: SymAuxArrayRepeat1, ReduceChildCount: 2},
		{Type: ts.ParseActionTypeShift, ShiftState: 10, ShiftRepetition: true},
 // [88]: REDUCE(SymAuxArrayRepeat1, 2)
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeReduce, ReduceSymbol: SymAuxArrayRepeat1, ReduceChildCount: 2},
 // [90]: REDUCE(SymPair, 3)
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeReduce, ReduceSymbol: SymPair, ReduceChildCount: 3, ReduceProdID: 1},
 // [92]: ACCEPT
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeAccept},
 // [94]: SHIFT(13)
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeShift, ShiftState: 13},
	}

	// --- Large state parse table (7 large states x 25 symbols) ---
	// For terminal symbols (0-14), entries are indices into parseActions.
	// For non-terminal symbols (15-24), entries are raw state IDs (goto targets).
	parseTable := []uint16{
		// State 0
		1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
		// State 1
		5, 7, 0, 0, 0, 9, 0, 11, 0, 0, 13, 13, 13, 13, 3, 30, 2, 8, 0, 8, 8, 0, 2, 0, 0,
		// State 2
		15, 7, 0, 0, 0, 9, 0, 11, 0, 0, 13, 13, 13, 13, 3, 0, 3, 8, 0, 8, 8, 0, 3, 0, 0,
		// State 3
		17, 19, 0, 0, 0, 22, 0, 25, 0, 0, 28, 28, 28, 28, 3, 0, 3, 8, 0, 8, 8, 0, 3, 0, 0,
		// State 4
		0, 7, 0, 0, 0, 9, 31, 11, 0, 0, 13, 13, 13, 13, 3, 0, 21, 8, 0, 8, 8, 0, 0, 0, 0,
		// State 5
		33, 33, 33, 33, 33, 33, 33, 33, 0, 0, 33, 33, 33, 33, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
		// State 6
		35, 35, 35, 35, 35, 35, 35, 35, 0, 0, 35, 35, 35, 35, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	}

	// --- Small parse table (compressed grouped format) ---
	// Format: for each small state: groupCount, then groups of (value, symCount, sym1, sym2, ...)
	smallParseTable := []uint16{
		// State 7 (small index 0, offset 0)
		2, // groupCount
		3, 1, 14, // group 1
		37, 11, 0, 1, 2, 3, 5, 6, 7, 10, 11, 12, 13, // group 2
		// State 8 (small index 1, offset 17)
		2, // groupCount
		3, 1, 14, // group 1
		39, 11, 0, 1, 2, 3, 5, 6, 7, 10, 11, 12, 13, // group 2
		// State 9 (small index 2, offset 34)
		2, // groupCount
		3, 1, 14, // group 1
		41, 11, 0, 1, 2, 3, 5, 6, 7, 10, 11, 12, 13, // group 2
		// State 10 (small index 3, offset 51)
		7, // groupCount
		3, 1, 14, // group 1
		7, 1, 1, // group 2
		9, 1, 5, // group 3
		11, 1, 7, // group 4
		29, 1, 16, // group 5
		8, 3, 17, 19, 20, // group 6
		13, 4, 10, 11, 12, 13, // group 7
		// State 11 (small index 4, offset 78)
		2, // groupCount
		3, 1, 14, // group 1
		43, 11, 0, 1, 2, 3, 5, 6, 7, 10, 11, 12, 13, // group 2
		// State 12 (small index 5, offset 95)
		2, // groupCount
		3, 1, 14, // group 1
		45, 11, 0, 1, 2, 3, 5, 6, 7, 10, 11, 12, 13, // group 2
		// State 13 (small index 6, offset 112)
		7, // groupCount
		3, 1, 14, // group 1
		7, 1, 1, // group 2
		9, 1, 5, // group 3
		11, 1, 7, // group 4
		28, 1, 16, // group 5
		8, 3, 17, 19, 20, // group 6
		13, 4, 10, 11, 12, 13, // group 7
		// State 14 (small index 7, offset 139)
		2, // groupCount
		3, 1, 14, // group 1
		47, 11, 0, 1, 2, 3, 5, 6, 7, 10, 11, 12, 13, // group 2
		// State 15 (small index 8, offset 156)
		2, // groupCount
		3, 1, 14, // group 1
		49, 11, 0, 1, 2, 3, 5, 6, 7, 10, 11, 12, 13, // group 2
		// State 16 (small index 9, offset 173)
		5, // groupCount
		3, 1, 14, // group 1
		11, 1, 7, // group 2
		51, 1, 3, // group 3
		20, 1, 18, // group 4
		31, 1, 20, // group 5
		// State 17 (small index 10, offset 189)
		4, // groupCount
		53, 1, 7, // group 1
		57, 1, 14, // group 2
		18, 1, 21, // group 3
		55, 2, 8, 9, // group 4
		// State 18 (small index 11, offset 203)
		4, // groupCount
		57, 1, 14, // group 1
		59, 1, 7, // group 2
		19, 1, 21, // group 3
		61, 2, 8, 9, // group 4
		// State 19 (small index 12, offset 217)
		4, // groupCount
		57, 1, 14, // group 1
		63, 1, 7, // group 2
		19, 1, 21, // group 3
		65, 2, 8, 9, // group 4
		// State 20 (small index 13, offset 231)
		4, // groupCount
		3, 1, 14, // group 1
		68, 1, 2, // group 2
		70, 1, 3, // group 3
		22, 1, 23, // group 4
		// State 21 (small index 14, offset 244)
		4, // groupCount
		3, 1, 14, // group 1
		72, 1, 2, // group 2
		74, 1, 6, // group 3
		24, 1, 24, // group 4
		// State 22 (small index 15, offset 257)
		4, // groupCount
		3, 1, 14, // group 1
		68, 1, 2, // group 2
		76, 1, 3, // group 3
		25, 1, 23, // group 4
		// State 23 (small index 16, offset 270)
		4, // groupCount
		3, 1, 14, // group 1
		11, 1, 7, // group 2
		27, 1, 18, // group 3
		31, 1, 20, // group 4
		// State 24 (small index 17, offset 283)
		4, // groupCount
		3, 1, 14, // group 1
		72, 1, 2, // group 2
		78, 1, 6, // group 3
		26, 1, 24, // group 4
		// State 25 (small index 18, offset 296)
		4, // groupCount
		3, 1, 14, // group 1
		80, 1, 2, // group 2
		83, 1, 3, // group 3
		25, 1, 23, // group 4
		// State 26 (small index 19, offset 309)
		4, // groupCount
		3, 1, 14, // group 1
		85, 1, 2, // group 2
		88, 1, 6, // group 3
		26, 1, 24, // group 4
		// State 27 (small index 20, offset 322)
		2, // groupCount
		3, 1, 14, // group 1
		83, 2, 2, 3, // group 2
		// State 28 (small index 21, offset 330)
		2, // groupCount
		3, 1, 14, // group 1
		90, 2, 2, 3, // group 2
		// State 29 (small index 22, offset 338)
		2, // groupCount
		3, 1, 14, // group 1
		88, 2, 2, 6, // group 2
		// State 30 (small index 23, offset 346)
		2, // groupCount
		3, 1, 14, // group 1
		92, 1, 0, // group 2
		// State 31 (small index 24, offset 353)
		2, // groupCount
		3, 1, 14, // group 1
		94, 1, 4, // group 2
	}

	smallParseTableMap := []uint32{
		0, // state 7 (small index 0)
		17, // state 8 (small index 1)
		34, // state 9 (small index 2)
		51, // state 10 (small index 3)
		78, // state 11 (small index 4)
		95, // state 12 (small index 5)
		112, // state 13 (small index 6)
		139, // state 14 (small index 7)
		156, // state 15 (small index 8)
		173, // state 16 (small index 9)
		189, // state 17 (small index 10)
		203, // state 18 (small index 11)
		217, // state 19 (small index 12)
		231, // state 20 (small index 13)
		244, // state 21 (small index 14)
		257, // state 22 (small index 15)
		270, // state 23 (small index 16)
		283, // state 24 (small index 17)
		296, // state 25 (small index 18)
		309, // state 26 (small index 19)
		322, // state 27 (small index 20)
		330, // state 28 (small index 21)
		338, // state 29 (small index 22)
		346, // state 30 (small index 23)
		353, // state 31 (small index 24)
	}

	// --- Lex modes ---
	lexModes := []ts.LexMode{
		{LexState: 0, ExternalLexState: 0}, // state 0
		{LexState: 0, ExternalLexState: 0}, // state 1
		{LexState: 0, ExternalLexState: 0}, // state 2
		{LexState: 0, ExternalLexState: 0}, // state 3
		{LexState: 0, ExternalLexState: 0}, // state 4
		{LexState: 0, ExternalLexState: 0}, // state 5
		{LexState: 0, ExternalLexState: 0}, // state 6
		{LexState: 0, ExternalLexState: 0}, // state 7
		{LexState: 0, ExternalLexState: 0}, // state 8
		{LexState: 0, ExternalLexState: 0}, // state 9
		{LexState: 0, ExternalLexState: 0}, // state 10
		{LexState: 0, ExternalLexState: 0}, // state 11
		{LexState: 0, ExternalLexState: 0}, // state 12
		{LexState: 0, ExternalLexState: 0}, // state 13
		{LexState: 0, ExternalLexState: 0}, // state 14
		{LexState: 0, ExternalLexState: 0}, // state 15
		{LexState: 0, ExternalLexState: 0}, // state 16
		{LexState: 1, ExternalLexState: 0}, // state 17
		{LexState: 1, ExternalLexState: 0}, // state 18
		{LexState: 1, ExternalLexState: 0}, // state 19
		{LexState: 0, ExternalLexState: 0}, // state 20
		{LexState: 0, ExternalLexState: 0}, // state 21
		{LexState: 0, ExternalLexState: 0}, // state 22
		{LexState: 0, ExternalLexState: 0}, // state 23
		{LexState: 0, ExternalLexState: 0}, // state 24
		{LexState: 0, ExternalLexState: 0}, // state 25
		{LexState: 0, ExternalLexState: 0}, // state 26
		{LexState: 0, ExternalLexState: 0}, // state 27
		{LexState: 0, ExternalLexState: 0}, // state 28
		{LexState: 0, ExternalLexState: 0}, // state 29
		{LexState: 0, ExternalLexState: 0}, // state 30
		{LexState: 0, ExternalLexState: 0}, // state 31
	}

	primaryStateIDs := []ts.StateID{
		0, // state 0
		1, // state 1
		2, // state 2
		3, // state 3
		4, // state 4
		5, // state 5
		6, // state 6
		7, // state 7
		8, // state 8
		9, // state 9
		10, // state 10
		11, // state 11
		12, // state 12
		13, // state 13
		14, // state 14
		15, // state 15
		16, // state 16
		17, // state 17
		18, // state 18
		19, // state 19
		20, // state 20
		21, // state 21
		22, // state 22
		23, // state 23
		24, // state 24
		25, // state 25
		26, // state 26
		27, // state 27
		28, // state 28
		29, // state 29
		30, // state 30
		31, // state 31
	}

	// Alias sequences: PRODUCTION_ID_COUNT * MAX_ALIAS_SEQUENCE_LENGTH entries.
	aliasSequences := make([]ts.Symbol, 2*4)

	return &ts.Language{
		Version:                14,
		SymbolCount:            symbolCount,
		AliasCount:             0,
		TokenCount:             15,
		ExternalTokenCount:     0,
		StateCount:             32,
		LargeStateCount:        7,
		ProductionIDCount:      2,
		FieldCount:             2,
		MaxAliasSequenceLength: 4,
		PrimaryStateIDs:        primaryStateIDs,

		ParseTable:         parseTable,
		SmallParseTable:    smallParseTable,
		SmallParseTableMap: smallParseTableMap,
		ParseActions:       parseActions,
		LexModes:           lexModes,

		// Lex functions are stubs for Phase 1.
		LexFn:        nil,
		KeywordLexFn: nil,

		SymbolNames: []string{
			"end", // 0
			"{", // 1
			",", // 2
			"}", // 3
			":", // 4
			"[", // 5
			"]", // 6
			"\"", // 7
			"string_content", // 8
			"escape_sequence", // 9
			"number", // 10
			"true", // 11
			"false", // 12
			"null", // 13
			"comment", // 14
			"document", // 15
			"_value", // 16
			"object", // 17
			"pair", // 18
			"array", // 19
			"string", // 20
			"_string_content", // 21
			"document_repeat1", // 22
			"object_repeat1", // 23
			"array_repeat1", // 24
		},

		SymbolMetadata: []ts.SymbolMetadata{
			{Visible: false, Named: true}, // 0: end
			{Visible: true, Named: false}, // 1: {
			{Visible: true, Named: false}, // 2: ,
			{Visible: true, Named: false}, // 3: }
			{Visible: true, Named: false}, // 4: :
			{Visible: true, Named: false}, // 5: [
			{Visible: true, Named: false}, // 6: ]
			{Visible: true, Named: false}, // 7: "
			{Visible: true, Named: true}, // 8: string_content
			{Visible: true, Named: true}, // 9: escape_sequence
			{Visible: true, Named: true}, // 10: number
			{Visible: true, Named: true}, // 11: true
			{Visible: true, Named: true}, // 12: false
			{Visible: true, Named: true}, // 13: null
			{Visible: true, Named: true}, // 14: comment
			{Visible: true, Named: true}, // 15: document
			{Visible: false, Named: true, Supertype: true}, // 16: _value
			{Visible: true, Named: true}, // 17: object
			{Visible: true, Named: true}, // 18: pair
			{Visible: true, Named: true}, // 19: array
			{Visible: true, Named: true}, // 20: string
			{Visible: false, Named: false}, // 21: _string_content
			{Visible: false, Named: false}, // 22: document_repeat1
			{Visible: false, Named: false}, // 23: object_repeat1
			{Visible: false, Named: false}, // 24: array_repeat1
		},

		// Field map: production 1 (pair) has key at child 0, value at child 2.
		FieldMapSlices: []ts.FieldMapSlice{
			{Index: 0, Length: 0}, // production 0: no fields
			{Index: 0, Length: 2}, // production 1: 2 field entries
		},
		FieldMapEntries: []ts.FieldMapEntry{
			{FieldID: FieldKey, ChildIndex: 0, Inherited: false},
			{FieldID: FieldValue, ChildIndex: 2, Inherited: false},
		},
		FieldNames: []string{
			"",      // 0: unused
			"key",   // 1
			"value", // 2
		},

		AliasSequences:   aliasSequences,
		SupertypeSymbols: []ts.Symbol{SymValue},
	}
}
