package generate

import (
	"fmt"
	"strings"
	"unicode"
)

// GenerateGo produces a Go source file that defines a Language for the given grammar.
func GenerateGo(g *Grammar, packageName string) string {
	var b strings.Builder

	// Header.
	fmt.Fprintf(&b, "// Code generated by tsgo-generate; DO NOT EDIT.\n")
	fmt.Fprintf(&b, "//\n")
	fmt.Fprintf(&b, "// Grammar: %s\n", g.Name)
	fmt.Fprintf(&b, "// Symbols: %d, States: %d (%d large, %d small)\n",
		g.SymbolCount, g.StateCount, g.LargeStateCount, g.StateCount-g.LargeStateCount)
	fmt.Fprintf(&b, "package %s\n\n", packageName)
	fmt.Fprintf(&b, "import ts \"github.com/treesitter-go/treesitter\"\n\n")

	// Symbol constants.
	writeSymbolConstants(&b, g)

	// Field constants.
	if g.FieldCount > 0 {
		writeFieldConstants(&b, g)
	}

	// Language function.
	funcName := exportedName(g.Name) + "Language"
	fmt.Fprintf(&b, "// %s returns the compiled %s grammar as a Language.\n", funcName, g.Name)
	fmt.Fprintf(&b, "func %s() *ts.Language {\n", funcName)

	// Parse actions.
	writeParseActions(&b, g)

	// Large parse table.
	writeParseTable(&b, g)

	// Small parse table.
	writeSmallParseTable(&b, g)

	// Small parse table map.
	writeSmallParseTableMap(&b, g)

	// Lex modes.
	writeLexModes(&b, g)

	// Primary state IDs.
	writePrimaryStateIDs(&b, g)

	// Alias sequences.
	writeAliasSequences(&b, g)

	// Symbol metadata.
	writeSymbolMetadata(&b, g)

	// Symbol names.
	writeSymbolNames(&b, g)

	// Field maps.
	writeFieldMaps(&b, g)

	// Supertype symbols.
	writeSuperTypes(&b, g)

	// External scanner data.
	writeExternalScannerData(&b, g)

	// Build the Language struct.
	fmt.Fprintf(&b, "\treturn &ts.Language{\n")
	fmt.Fprintf(&b, "\t\tVersion:                14,\n")
	fmt.Fprintf(&b, "\t\tSymbolCount:            %d,\n", g.SymbolCount)
	fmt.Fprintf(&b, "\t\tAliasCount:             %d,\n", g.AliasCount)
	fmt.Fprintf(&b, "\t\tTokenCount:             %d,\n", g.TokenCount)
	fmt.Fprintf(&b, "\t\tExternalTokenCount:     %d,\n", g.ExternalTokenCount)
	fmt.Fprintf(&b, "\t\tStateCount:             %d,\n", g.StateCount)
	fmt.Fprintf(&b, "\t\tLargeStateCount:        %d,\n", g.LargeStateCount)
	fmt.Fprintf(&b, "\t\tProductionIDCount:      %d,\n", g.ProductionIDCount)
	fmt.Fprintf(&b, "\t\tFieldCount:             %d,\n", g.FieldCount)
	fmt.Fprintf(&b, "\t\tMaxAliasSequenceLength: %d,\n", g.MaxAliasSequenceLength)
	fmt.Fprintf(&b, "\t\tPrimaryStateIDs:        primaryStateIDs,\n")
	fmt.Fprintf(&b, "\t\tParseTable:             parseTable,\n")
	fmt.Fprintf(&b, "\t\tSmallParseTable:        smallParseTable,\n")
	fmt.Fprintf(&b, "\t\tSmallParseTableMap:     smallParseTableMap,\n")
	fmt.Fprintf(&b, "\t\tParseActions:           parseActions,\n")
	fmt.Fprintf(&b, "\t\tLexModes:               lexModes,\n")
	fmt.Fprintf(&b, "\t\tLexFn:                  tsLex,\n")
	if len(g.KeywordLexStates) > 0 {
		fmt.Fprintf(&b, "\t\tKeywordLexFn:           tsLexKeywords,\n")
		fmt.Fprintf(&b, "\t\tKeywordCaptureToken:    ts.Symbol(%d),\n", g.KeywordCaptureToken)
	}
	fmt.Fprintf(&b, "\t\tSymbolNames:            symbolNames,\n")
	fmt.Fprintf(&b, "\t\tSymbolMetadata:          symbolMetadata,\n")
	if g.FieldCount > 0 {
		fmt.Fprintf(&b, "\t\tFieldMapSlices:         fieldMapSlices,\n")
		fmt.Fprintf(&b, "\t\tFieldMapEntries:        fieldMapEntries,\n")
		fmt.Fprintf(&b, "\t\tFieldNames:             fieldNames,\n")
	}
	fmt.Fprintf(&b, "\t\tAliasSequences:         aliasSequences,\n")
	// Check for supertype symbols from metadata.
	hasSupertypes := false
	for _, m := range g.SymbolMetadata {
		if m.Supertype {
			hasSupertypes = true
			break
		}
	}
	if hasSupertypes {
		fmt.Fprintf(&b, "\t\tSupertypeSymbols:       supertypeSymbols,\n")
	}
	if len(g.ExternalScannerStates) > 0 {
		fmt.Fprintf(&b, "\t\tExternalScannerStates:  externalScannerStates,\n")
	}
	if len(g.ExternalSymbolMap) > 0 {
		fmt.Fprintf(&b, "\t\tExternalSymbolMap:      externalSymbolMap,\n")
	}
	fmt.Fprintf(&b, "\t}\n")
	fmt.Fprintf(&b, "}\n\n")

	// Character range sets (for set_contains in lex functions).
	if len(g.CharacterSets) > 0 {
		writeCharacterSets(&b, g)
		writeSetContainsFunc(&b)
	}

	// Lex function.
	writeLexFunction(&b, g, false)

	// Keyword lex function.
	if len(g.KeywordLexStates) > 0 {
		writeLexFunction(&b, g, true)
	}

	return b.String()
}

// writeSymbolConstants writes the symbol constant block.
// writeFieldConstants writes field constant block.
func writeFieldConstants(b *strings.Builder, g *Grammar) {
	fmt.Fprintf(b, "// Grammar field IDs.\n")
	fmt.Fprintf(b, "const (\n")
	for i, name := range g.FieldNames {
		if i == 0 || name == "" {
			continue
		}
		constName := "Field" + exportedName(name)
		fmt.Fprintf(b, "\t%s ts.FieldID = %d\n", constName, i)
	}
	fmt.Fprintf(b, ")\n\n")
}

// writeParseActions writes the parse actions array.
func writeParseActions(b *strings.Builder, g *Grammar) {
	fmt.Fprintf(b, "\tparseActions := []ts.ParseActionEntry{\n")
	for i, a := range g.ParseActions {
		if a.IsHeader {
			reusable := "false"
			if a.Reusable {
				reusable = "true"
			}
			fmt.Fprintf(b, "\t\t// [%d]\n", i)
			fmt.Fprintf(b, "\t\t{Type: ts.ParseActionTypeHeader, Count: %d, Reusable: %s},\n", a.Count, reusable)
		} else {
			switch a.ActionType {
			case "shift":
				if a.ShiftExtra {
					fmt.Fprintf(b, "\t\t{Type: ts.ParseActionTypeShift, ShiftExtra: true},\n")
				} else if a.ShiftRepetition {
					fmt.Fprintf(b, "\t\t{Type: ts.ParseActionTypeShift, ShiftState: %d, ShiftRepetition: true},\n", a.ShiftState)
				} else {
					fmt.Fprintf(b, "\t\t{Type: ts.ParseActionTypeShift, ShiftState: %d},\n", a.ShiftState)
				}
			case "reduce":
				s := fmt.Sprintf("\t\t{Type: ts.ParseActionTypeReduce, ReduceSymbol: %d, ReduceChildCount: %d", a.ReduceSymbol, a.ReduceChildCount)
				if a.ReduceDynPrec != 0 {
					s += fmt.Sprintf(", ReduceDynPrec: %d", a.ReduceDynPrec)
				}
				if a.ReduceProdID != 0 {
					s += fmt.Sprintf(", ReduceProdID: %d", a.ReduceProdID)
				}
				s += "},\n"
				fmt.Fprint(b, s)
			case "accept":
				fmt.Fprintf(b, "\t\t{Type: ts.ParseActionTypeAccept},\n")
			case "recover":
				fmt.Fprintf(b, "\t\t{Type: ts.ParseActionTypeRecover},\n")
			}
		}
	}
	fmt.Fprintf(b, "\t}\n\n")
}

// writeParseTable writes the large state parse table.
func writeParseTable(b *strings.Builder, g *Grammar) {
	fmt.Fprintf(b, "\tparseTable := []uint16{\n")
	for s := 0; s < g.LargeStateCount; s++ {
		fmt.Fprintf(b, "\t\t// State %d\n\t\t", s)
		for i := 0; i < g.SymbolCount; i++ {
			idx := s*g.SymbolCount + i
			if idx < len(g.ParseTable) {
				fmt.Fprintf(b, "%d, ", g.ParseTable[idx])
			}
		}
		fmt.Fprintln(b)
	}
	fmt.Fprintf(b, "\t}\n\n")
}

// writeSmallParseTable writes the small parse table.
func writeSmallParseTable(b *strings.Builder, g *Grammar) {
	fmt.Fprintf(b, "\tsmallParseTable := []uint16{\n\t\t")
	for i, v := range g.SmallParseTable {
		fmt.Fprintf(b, "%d, ", v)
		if (i+1)%20 == 0 {
			fmt.Fprintf(b, "\n\t\t")
		}
	}
	fmt.Fprintf(b, "\n\t}\n\n")
}

// writeSmallParseTableMap writes the small parse table map.
func writeSmallParseTableMap(b *strings.Builder, g *Grammar) {
	fmt.Fprintf(b, "\tsmallParseTableMap := []uint32{")
	for i, v := range g.SmallParseTableMap {
		if i%10 == 0 {
			fmt.Fprintf(b, "\n\t\t")
		}
		fmt.Fprintf(b, "%d, ", v)
	}
	fmt.Fprintf(b, "\n\t}\n\n")
}

// writeLexModes writes the lex modes array.
func writeLexModes(b *strings.Builder, g *Grammar) {
	fmt.Fprintf(b, "\tlexModes := []ts.LexMode{\n")
	for i, lm := range g.LexModes {
		if lm.ExternalLexState != 0 {
			fmt.Fprintf(b, "\t\t{LexState: %d, ExternalLexState: %d}, // state %d\n", lm.LexState, lm.ExternalLexState, i)
		} else {
			fmt.Fprintf(b, "\t\t{LexState: %d}, // state %d\n", lm.LexState, i)
		}
	}
	fmt.Fprintf(b, "\t}\n\n")
}

// writePrimaryStateIDs writes the primary state IDs array.
func writePrimaryStateIDs(b *strings.Builder, g *Grammar) {
	fmt.Fprintf(b, "\tprimaryStateIDs := []ts.StateID{")
	for i, id := range g.PrimaryStateIDs {
		if i%10 == 0 {
			fmt.Fprintf(b, "\n\t\t")
		}
		fmt.Fprintf(b, "%d, ", id)
	}
	fmt.Fprintf(b, "\n\t}\n\n")
}

// writeAliasSequences writes the alias sequences array.
func writeAliasSequences(b *strings.Builder, g *Grammar) {
	size := g.ProductionIDCount * g.MaxAliasSequenceLength
	if size == 0 {
		fmt.Fprintf(b, "\taliasSequences := make([]ts.Symbol, 0)\n\n")
		return
	}
	fmt.Fprintf(b, "\taliasSequences := make([]ts.Symbol, %d)\n", size)
	// Write non-zero entries.
	hasNonZero := false
	for i, v := range g.AliasSequences {
		if v != 0 && i < size {
			fmt.Fprintf(b, "\taliasSequences[%d] = %d\n", i, v)
			hasNonZero = true
		}
	}
	if !hasNonZero {
		fmt.Fprintf(b, "\t_ = aliasSequences\n")
	}
	fmt.Fprintln(b)
}

// writeSymbolMetadata writes the symbol metadata array.
func writeSymbolMetadata(b *strings.Builder, g *Grammar) {
	fmt.Fprintf(b, "\tsymbolMetadata := []ts.SymbolMetadata{\n")
	for i, m := range g.SymbolMetadata {
		name := ""
		if i < len(g.SymbolNames) {
			name = g.SymbolNames[i]
		}
		fmt.Fprintf(b, "\t\t{Visible: %t, Named: %t", m.Visible, m.Named)
		if m.Supertype {
			fmt.Fprintf(b, ", Supertype: true")
		}
		fmt.Fprintf(b, "}, // %d: %s\n", i, name)
	}
	fmt.Fprintf(b, "\t}\n\n")
}

// writeSymbolNames writes the symbol names array.
func writeSymbolNames(b *strings.Builder, g *Grammar) {
	fmt.Fprintf(b, "\tsymbolNames := []string{\n")
	for i, name := range g.SymbolNames {
		fmt.Fprintf(b, "\t\t%q, // %d\n", name, i)
	}
	fmt.Fprintf(b, "\t}\n\n")
}

// writeFieldMaps writes the field map slices and entries.
func writeFieldMaps(b *strings.Builder, g *Grammar) {
	if g.FieldCount == 0 {
		return
	}

	fmt.Fprintf(b, "\tfieldMapSlices := []ts.FieldMapSlice{\n")
	for _, s := range g.FieldMapSlices {
		fmt.Fprintf(b, "\t\t{Index: %d, Length: %d},\n", s.Index, s.Length)
	}
	fmt.Fprintf(b, "\t}\n\n")

	fmt.Fprintf(b, "\tfieldMapEntries := []ts.FieldMapEntry{\n")
	for _, e := range g.FieldMapEntries {
		if e.Inherited {
			fmt.Fprintf(b, "\t\t{FieldID: %d, ChildIndex: %d, Inherited: true},\n", e.FieldID, e.ChildIndex)
		} else {
			fmt.Fprintf(b, "\t\t{FieldID: %d, ChildIndex: %d},\n", e.FieldID, e.ChildIndex)
		}
	}
	fmt.Fprintf(b, "\t}\n\n")

	fmt.Fprintf(b, "\tfieldNames := []string{\n")
	for _, name := range g.FieldNames {
		fmt.Fprintf(b, "\t\t%q,\n", name)
	}
	fmt.Fprintf(b, "\t}\n\n")
}

// writeSuperTypes writes the supertype symbols array.
func writeSuperTypes(b *strings.Builder, g *Grammar) {
	// Find supertype symbols from metadata.
	var supertypes []int
	for i, m := range g.SymbolMetadata {
		if m.Supertype {
			supertypes = append(supertypes, i)
		}
	}
	if len(supertypes) == 0 {
		return
	}
	fmt.Fprintf(b, "\tsupertypeSymbols := []ts.Symbol{")
	for _, s := range supertypes {
		fmt.Fprintf(b, "%d, ", s)
	}
	fmt.Fprintf(b, "}\n\n")
}

// writeExternalScannerData writes external scanner states and symbol map.
func writeExternalScannerData(b *strings.Builder, g *Grammar) {
	if len(g.ExternalScannerStates) > 0 {
		fmt.Fprintf(b, "\texternalScannerStates := []bool{")
		for i, v := range g.ExternalScannerStates {
			if i%20 == 0 {
				fmt.Fprintf(b, "\n\t\t")
			}
			if v {
				fmt.Fprintf(b, "true, ")
			} else {
				fmt.Fprintf(b, "false, ")
			}
		}
		fmt.Fprintf(b, "\n\t}\n\n")
	}

	if len(g.ExternalSymbolMap) > 0 {
		fmt.Fprintf(b, "\texternalSymbolMap := []ts.Symbol{")
		for _, s := range g.ExternalSymbolMap {
			fmt.Fprintf(b, "%d, ", s)
		}
		fmt.Fprintf(b, "}\n\n")
	}
}

// writeLexFunction generates the Go lex function from DFA states.
func writeLexFunction(b *strings.Builder, g *Grammar, isKeyword bool) {
	var funcName string
	var states []LexState
	if isKeyword {
		funcName = "tsLexKeywords"
		states = g.KeywordLexStates
	} else {
		funcName = "tsLex"
		states = g.LexStates
	}

	fmt.Fprintf(b, "func %s(lexer *ts.Lexer, state ts.StateID) bool {\n", funcName)
	fmt.Fprintf(b, "\tlookahead := lexer.Lookahead\n")
	fmt.Fprintf(b, "\teof := lexer.EOF()\n")
	fmt.Fprintf(b, "\t_ = eof\n\n")
	fmt.Fprintf(b, "\tfor {\n")
	fmt.Fprintf(b, "\t\tswitch state {\n")

	for _, s := range states {
		fmt.Fprintf(b, "\t\tcase %d:\n", s.ID)

		// Accept token if this is an accepting state.
		if s.AcceptToken != 0 {
			fmt.Fprintf(b, "\t\t\tlexer.MarkEnd()\n")
			fmt.Fprintf(b, "\t\t\tlexer.AcceptToken(%d)\n", s.AcceptToken)
		}

		// EOF check.
		if s.HasEOFCheck {
			if s.EOFAccept {
				fmt.Fprintf(b, "\t\t\tif eof {\n")
				fmt.Fprintf(b, "\t\t\t\tlexer.MarkEnd()\n")
				fmt.Fprintf(b, "\t\t\t\tlexer.AcceptToken(%d)\n", s.EOFAcceptToken)
				fmt.Fprintf(b, "\t\t\t\treturn true\n")
				fmt.Fprintf(b, "\t\t\t}\n")
			} else {
				fmt.Fprintf(b, "\t\t\tif eof {\n")
				fmt.Fprintf(b, "\t\t\t\tstate = %d\n", s.EOFTarget)
				fmt.Fprintf(b, "\t\t\t\tlexer.Advance(false)\n")
				fmt.Fprintf(b, "\t\t\t\tlookahead = lexer.Lookahead\n")
				fmt.Fprintf(b, "\t\t\t\teof = lexer.EOF()\n")
				fmt.Fprintf(b, "\t\t\t\tcontinue\n")
				fmt.Fprintf(b, "\t\t\t}\n")
			}
		}

		// Character transitions.
		if len(s.Transitions) > 0 {
			for _, t := range s.Transitions {
				advanceCall := "false"
				if t.Skip {
					advanceCall = "true"
				}

				if t.CharSetName != "" {
					fmt.Fprintf(b, "\t\t\tif setContains(%s, lookahead) {\n", t.CharSetName)
				} else if t.IsRange {
					fmt.Fprintf(b, "\t\t\tif lookahead >= %s && lookahead <= %s {\n",
						goCharLit(t.Low), goCharLit(t.High))
				} else if t.IsNegated && len(t.CharExclusions) > 0 {
					// Compound negation: exclude multiple chars/EOF.
					var conditions []string
					for _, ex := range t.CharExclusions {
						if ex == 0 {
							conditions = append(conditions, "!eof")
						} else {
							conditions = append(conditions, fmt.Sprintf("lookahead != %s", goCharLit(ex)))
						}
					}
					fmt.Fprintf(b, "\t\t\tif %s {\n", strings.Join(conditions, " && "))
				} else if t.IsNegated {
					if t.Char == 0 {
						fmt.Fprintf(b, "\t\t\tif !eof {\n")
					} else {
						fmt.Fprintf(b, "\t\t\tif lookahead != %s {\n", goCharLit(t.Char))
					}
				} else {
					fmt.Fprintf(b, "\t\t\tif lookahead == %s {\n", goCharLit(t.Char))
				}
				fmt.Fprintf(b, "\t\t\t\tstate = %d\n", t.Target)
				fmt.Fprintf(b, "\t\t\t\tlexer.Advance(%s)\n", advanceCall)
				fmt.Fprintf(b, "\t\t\t\tlookahead = lexer.Lookahead\n")
				fmt.Fprintf(b, "\t\t\t\teof = lexer.EOF()\n")
				fmt.Fprintf(b, "\t\t\t\tcontinue\n")
				fmt.Fprintf(b, "\t\t\t}\n")
			}
		}

		// Default transition (catch-all).
		if s.HasDefault {
			advanceCall := "false"
			if s.DefaultSkip {
				advanceCall = "true"
			}
			fmt.Fprintf(b, "\t\t\tif !eof {\n")
			fmt.Fprintf(b, "\t\t\t\tstate = %d\n", s.DefaultTarget)
			fmt.Fprintf(b, "\t\t\t\tlexer.Advance(%s)\n", advanceCall)
			fmt.Fprintf(b, "\t\t\t\tlookahead = lexer.Lookahead\n")
			fmt.Fprintf(b, "\t\t\t\teof = lexer.EOF()\n")
			fmt.Fprintf(b, "\t\t\t\tcontinue\n")
			fmt.Fprintf(b, "\t\t\t}\n")
		}

		// Return.
		if s.AcceptToken != 0 {
			fmt.Fprintf(b, "\t\t\treturn true\n")
		} else {
			fmt.Fprintf(b, "\t\t\treturn false\n")
		}
	}

	fmt.Fprintf(b, "\t\tdefault:\n")
	fmt.Fprintf(b, "\t\t\treturn false\n")
	fmt.Fprintf(b, "\t\t}\n")
	fmt.Fprintf(b, "\t}\n")
	fmt.Fprintf(b, "}\n\n")
}

// writeCharacterSets generates Go variable declarations for character range sets.
func writeCharacterSets(b *strings.Builder, g *Grammar) {
	// Sort set names for deterministic output.
	var names []string
	for name := range g.CharacterSets {
		names = append(names, name)
	}
	sortStrings(names)

	for _, name := range names {
		ranges := g.CharacterSets[name]
		fmt.Fprintf(b, "var %s = []characterRange{\n", name)
		for _, r := range ranges {
			fmt.Fprintf(b, "\t{0x%x, 0x%x},\n", r.Low, r.High)
		}
		fmt.Fprintf(b, "}\n\n")
	}
}

// writeSetContainsFunc generates the setContains helper function
// that does binary search over sorted character range arrays.
func writeSetContainsFunc(b *strings.Builder) {
	fmt.Fprintf(b, "type characterRange struct {\n")
	fmt.Fprintf(b, "\tlow  rune\n")
	fmt.Fprintf(b, "\thigh rune\n")
	fmt.Fprintf(b, "}\n\n")
	fmt.Fprintf(b, "func setContains(ranges []characterRange, c rune) bool {\n")
	fmt.Fprintf(b, "\tlo, hi := 0, len(ranges)\n")
	fmt.Fprintf(b, "\tfor lo < hi {\n")
	fmt.Fprintf(b, "\t\tmid := lo + (hi-lo)/2\n")
	fmt.Fprintf(b, "\t\tif c < ranges[mid].low {\n")
	fmt.Fprintf(b, "\t\t\thi = mid\n")
	fmt.Fprintf(b, "\t\t} else if c > ranges[mid].high {\n")
	fmt.Fprintf(b, "\t\t\tlo = mid + 1\n")
	fmt.Fprintf(b, "\t\t} else {\n")
	fmt.Fprintf(b, "\t\t\treturn true\n")
	fmt.Fprintf(b, "\t\t}\n")
	fmt.Fprintf(b, "\t}\n")
	fmt.Fprintf(b, "\treturn false\n")
	fmt.Fprintf(b, "}\n\n")
}

// sortStrings sorts a slice of strings in place.
func sortStrings(s []string) {
	for i := 1; i < len(s); i++ {
		for j := i; j > 0 && s[j-1] > s[j]; j-- {
			s[j-1], s[j] = s[j], s[j-1]
		}
	}
}

// --- Helpers ---

// writeSymbolConstants writes the symbol constant block, handling name collisions.
func writeSymbolConstants(b *strings.Builder, g *Grammar) {
	// Generate names and detect collisions.
	names := make([]string, len(g.SymbolNames))
	seen := make(map[string]bool)

	for i, name := range g.SymbolNames {
		constName := symbolConstNameBase(name, i)
		if seen[constName] {
			// Collision: add index suffix to disambiguate.
			constName = fmt.Sprintf("%s%d", constName, i)
		}
		seen[constName] = true
		names[i] = constName
	}

	fmt.Fprintf(b, "// Grammar symbol IDs.\n")
	fmt.Fprintf(b, "const (\n")
	for i, constName := range names {
		fmt.Fprintf(b, "\t%s ts.Symbol = %d\n", constName, i)
	}
	fmt.Fprintf(b, ")\n\n")
}

// symbolConstNameBase converts a symbol name to a Go constant name.
func symbolConstNameBase(name string, index int) string {
	if name == "" {
		return fmt.Sprintf("Sym%d", index)
	}

	// Special cases for builtin symbols.
	switch name {
	case "end":
		return "SymEnd"
	case "ERROR":
		return "SymError"
	}

	// Punctuation mapping.
	if isPunctuation(name) {
		return "Sym" + punctuationName(name)
	}

	// Hidden/aux symbols: prefix with _ in tree-sitter.
	prefix := "Sym"
	cleanName := name
	if strings.HasPrefix(name, "_") {
		cleanName = name[1:]
		prefix = "SymAux"
	}

	// After stripping prefix, the clean name might be punctuation.
	if isPunctuation(cleanName) {
		return prefix + punctuationName(cleanName)
	}

	return prefix + exportedName(cleanName)
}

// exportedName converts a name to exported Go identifier (PascalCase).
func exportedName(name string) string {
	if name == "" {
		return ""
	}
	parts := strings.FieldsFunc(name, func(r rune) bool {
		return r == '_' || r == '-' || r == '.' || r == ' '
	})
	var result strings.Builder
	for _, p := range parts {
		if p == "" {
			continue
		}
		// Strip non-identifier characters from each part.
		var clean []rune
		for _, r := range p {
			if unicode.IsLetter(r) || unicode.IsDigit(r) {
				clean = append(clean, r)
			}
		}
		if len(clean) == 0 {
			continue
		}
		clean[0] = unicode.ToUpper(clean[0])
		result.WriteString(string(clean))
	}
	return result.String()
}

// isPunctuation checks if a symbol name is punctuation.
func isPunctuation(name string) bool {
	for _, r := range name {
		if unicode.IsLetter(r) || r == '_' {
			return false
		}
	}
	return true
}

// punctuationName maps a punctuation symbol to a readable constant name.
func punctuationName(name string) string {
	mapping := map[string]string{
		"{":  "LBrace",
		"}":  "RBrace",
		"[":  "LBrack",
		"]":  "RBrack",
		"(":  "LParen",
		")":  "RParen",
		",":  "Comma",
		":":  "Colon",
		";":  "Semi",
		".":  "Dot",
		"\"": "DQuote",
		"'":  "SQuote",
		"`":  "Backtick",
		"=":  "Eq",
		"!":  "Bang",
		"<":  "Lt",
		">":  "Gt",
		"+":  "Plus",
		"-":  "Minus",
		"*":  "Star",
		"/":  "Slash",
		"%":  "Percent",
		"&":  "Amp",
		"|":  "Pipe",
		"^":  "Caret",
		"~":  "Tilde",
		"?":  "Question",
		"@":  "At",
		"#":  "Hash",
		"$":  "Dollar",
		"\\": "Backslash",
		"==": "EqEq",
		"!=": "BangEq",
		"<=": "LtEq",
		">=": "GtEq",
		"&&": "AmpAmp",
		"||": "PipePipe",
		"<<": "LtLt",
		">>": "GtGt",
		"++": "PlusPlus",
		"--": "MinusMinus",
		"->": "Arrow",
		"=>": "FatArrow",
		"::": "ColonColon",
		"..": "DotDot",
		"...": "Ellipsis",
	}
	if n, ok := mapping[name]; ok {
		return n
	}
	// Fallback: build from individual chars.
	var result strings.Builder
	for _, r := range name {
		if n, ok := mapping[string(r)]; ok {
			result.WriteString(n)
		} else if unicode.IsLetter(r) || unicode.IsDigit(r) {
			result.WriteRune(r)
		} else {
			// Non-letter, non-mapped: use Unicode code point.
			fmt.Fprintf(&result, "U%04X", r)
		}
	}
	return result.String()
}

// goCharLit returns a Go character literal for a rune.
func goCharLit(r rune) string {
	if r == 0 {
		return "0"
	}
	if r == '\'' {
		return `'\''`
	}
	if r == '\\' {
		return `'\\'`
	}
	if r == '\n' {
		return `'\n'`
	}
	if r == '\t' {
		return `'\t'`
	}
	if r == '\r' {
		return `'\r'`
	}
	if r == '\a' {
		return `'\a'`
	}
	if r == '\b' {
		return `'\b'`
	}
	if r == '\f' {
		return `'\f'`
	}
	if r == '\v' {
		return `'\v'`
	}
	if r >= 0x20 && r < 0x7f {
		return fmt.Sprintf("'%c'", r)
	}
	// Non-printable or Unicode: use hex or unicode escape.
	if r < 0x100 {
		return fmt.Sprintf("0x%02x", r)
	}
	return fmt.Sprintf("0x%04x", r)
}
