// Code generated by tsgo-generate; DO NOT EDIT.
//
// Grammar: html
// Symbols: 41, States: 94 (2 large, 92 small)
package html

import ts "github.com/treesitter-go/treesitter"

// Grammar symbol IDs.
const (
	SymEnd ts.Symbol = 0
	SymLtBang ts.Symbol = 1
	SymDoctypeToken1 ts.Symbol = 2
	SymGt ts.Symbol = 3
	SymDoctype ts.Symbol = 4
	SymLt ts.Symbol = 5
	SymSlashGt ts.Symbol = 6
	SymLtSlash ts.Symbol = 7
	SymEq ts.Symbol = 8
	SymAttributeName ts.Symbol = 9
	SymAttributeValue ts.Symbol = 10
	SymEntity ts.Symbol = 11
	SymSQuote ts.Symbol = 12
	SymAttributeValue13 ts.Symbol = 13
	SymDQuote ts.Symbol = 14
	SymAttributeValue15 ts.Symbol = 15
	SymText ts.Symbol = 16
	SymTagName ts.Symbol = 17
	SymTagName18 ts.Symbol = 18
	SymTagName19 ts.Symbol = 19
	SymTagName20 ts.Symbol = 20
	SymErroneousEndTagName ts.Symbol = 21
	SymAuxImplicitEndTag ts.Symbol = 22
	SymRawText ts.Symbol = 23
	SymComment ts.Symbol = 24
	SymDocument ts.Symbol = 25
	SymDoctype26 ts.Symbol = 26
	SymAuxNode ts.Symbol = 27
	SymElement ts.Symbol = 28
	SymScriptElement ts.Symbol = 29
	SymStyleElement ts.Symbol = 30
	SymStartTag ts.Symbol = 31
	SymStartTag32 ts.Symbol = 32
	SymStartTag33 ts.Symbol = 33
	SymSelfClosingTag ts.Symbol = 34
	SymEndTag ts.Symbol = 35
	SymErroneousEndTag ts.Symbol = 36
	SymAttribute ts.Symbol = 37
	SymQuotedAttributeValue ts.Symbol = 38
	SymDocumentRepeat1 ts.Symbol = 39
	SymStartTagRepeat1 ts.Symbol = 40
)

// HtmlLanguage returns the compiled html grammar as a Language.
func HtmlLanguage() *ts.Language {
	parseActions := []ts.ParseActionEntry{
		// [0]
		{Type: ts.ParseActionTypeHeader, Count: 0, Reusable: false},
		// [1]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: false},
		{Type: ts.ParseActionTypeRecover},
		// [3]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeShift, ShiftExtra: true},
		// [5]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeReduce, ReduceSymbol: 25, ReduceChildCount: 0},
		// [7]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeShift, ShiftState: 77},
		// [9]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: false},
		{Type: ts.ParseActionTypeShift, ShiftState: 52},
		// [11]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeShift, ShiftState: 85},
		// [13]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeShift, ShiftState: 7},
		// [15]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeShift, ShiftState: 93},
		// [17]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: false},
		{Type: ts.ParseActionTypeShift, ShiftState: 57},
		// [19]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeShift, ShiftState: 68},
		// [21]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeShift, ShiftState: 3},
		// [23]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeShift, ShiftState: 32},
		// [25]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeShift, ShiftState: 6},
		// [27]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeShift, ShiftState: 14},
		// [29]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeShift, ShiftState: 59},
		// [31]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeShift, ShiftState: 27},
		// [33]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeShift, ShiftState: 4},
		// [35]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeShift, ShiftState: 22},
		// [37]
		{Type: ts.ParseActionTypeHeader, Count: 2, Reusable: true},
		{Type: ts.ParseActionTypeShift, ShiftState: 93, ShiftRepetition: true},
		{Type: ts.ParseActionTypeReduce, ReduceSymbol: 39, ReduceChildCount: 2},
		// [40]
		{Type: ts.ParseActionTypeHeader, Count: 2, Reusable: false},
		{Type: ts.ParseActionTypeShift, ShiftState: 57, ShiftRepetition: true},
		{Type: ts.ParseActionTypeReduce, ReduceSymbol: 39, ReduceChildCount: 2},
		// [43]
		{Type: ts.ParseActionTypeHeader, Count: 2, Reusable: true},
		{Type: ts.ParseActionTypeShift, ShiftState: 89, ShiftRepetition: true},
		{Type: ts.ParseActionTypeReduce, ReduceSymbol: 39, ReduceChildCount: 2},
		// [46]
		{Type: ts.ParseActionTypeHeader, Count: 2, Reusable: true},
		{Type: ts.ParseActionTypeShift, ShiftState: 6, ShiftRepetition: true},
		{Type: ts.ParseActionTypeReduce, ReduceSymbol: 39, ReduceChildCount: 2},
		// [49]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeReduce, ReduceSymbol: 39, ReduceChildCount: 2},
		// [51]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeReduce, ReduceSymbol: 25, ReduceChildCount: 1},
		// [53]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeShift, ShiftState: 8},
		// [55]
		{Type: ts.ParseActionTypeHeader, Count: 2, Reusable: true},
		{Type: ts.ParseActionTypeShift, ShiftState: 77, ShiftRepetition: true},
		{Type: ts.ParseActionTypeReduce, ReduceSymbol: 39, ReduceChildCount: 2},
		// [58]
		{Type: ts.ParseActionTypeHeader, Count: 2, Reusable: false},
		{Type: ts.ParseActionTypeShift, ShiftState: 52, ShiftRepetition: true},
		{Type: ts.ParseActionTypeReduce, ReduceSymbol: 39, ReduceChildCount: 2},
		// [61]
		{Type: ts.ParseActionTypeHeader, Count: 2, Reusable: true},
		{Type: ts.ParseActionTypeShift, ShiftState: 85, ShiftRepetition: true},
		{Type: ts.ParseActionTypeReduce, ReduceSymbol: 39, ReduceChildCount: 2},
		// [64]
		{Type: ts.ParseActionTypeHeader, Count: 2, Reusable: true},
		{Type: ts.ParseActionTypeShift, ShiftState: 8, ShiftRepetition: true},
		{Type: ts.ParseActionTypeReduce, ReduceSymbol: 39, ReduceChildCount: 2},
		// [67]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeReduce, ReduceSymbol: 35, ReduceChildCount: 3},
		// [69]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: false},
		{Type: ts.ParseActionTypeReduce, ReduceSymbol: 35, ReduceChildCount: 3},
		// [71]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeReduce, ReduceSymbol: 30, ReduceChildCount: 2},
		// [73]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: false},
		{Type: ts.ParseActionTypeReduce, ReduceSymbol: 30, ReduceChildCount: 2},
		// [75]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeReduce, ReduceSymbol: 31, ReduceChildCount: 3},
		// [77]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: false},
		{Type: ts.ParseActionTypeReduce, ReduceSymbol: 31, ReduceChildCount: 3},
		// [79]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeReduce, ReduceSymbol: 34, ReduceChildCount: 3},
		// [81]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: false},
		{Type: ts.ParseActionTypeReduce, ReduceSymbol: 34, ReduceChildCount: 3},
		// [83]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeReduce, ReduceSymbol: 36, ReduceChildCount: 3},
		// [85]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: false},
		{Type: ts.ParseActionTypeReduce, ReduceSymbol: 36, ReduceChildCount: 3},
		// [87]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeReduce, ReduceSymbol: 28, ReduceChildCount: 3},
		// [89]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: false},
		{Type: ts.ParseActionTypeReduce, ReduceSymbol: 28, ReduceChildCount: 3},
		// [91]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeReduce, ReduceSymbol: 29, ReduceChildCount: 3},
		// [93]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: false},
		{Type: ts.ParseActionTypeReduce, ReduceSymbol: 29, ReduceChildCount: 3},
		// [95]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeReduce, ReduceSymbol: 30, ReduceChildCount: 3},
		// [97]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: false},
		{Type: ts.ParseActionTypeReduce, ReduceSymbol: 30, ReduceChildCount: 3},
		// [99]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeReduce, ReduceSymbol: 26, ReduceChildCount: 4},
		// [101]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: false},
		{Type: ts.ParseActionTypeReduce, ReduceSymbol: 26, ReduceChildCount: 4},
		// [103]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeReduce, ReduceSymbol: 31, ReduceChildCount: 4},
		// [105]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: false},
		{Type: ts.ParseActionTypeReduce, ReduceSymbol: 31, ReduceChildCount: 4},
		// [107]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeReduce, ReduceSymbol: 29, ReduceChildCount: 2},
		// [109]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: false},
		{Type: ts.ParseActionTypeReduce, ReduceSymbol: 29, ReduceChildCount: 2},
		// [111]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeReduce, ReduceSymbol: 28, ReduceChildCount: 1},
		// [113]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: false},
		{Type: ts.ParseActionTypeReduce, ReduceSymbol: 28, ReduceChildCount: 1},
		// [115]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeReduce, ReduceSymbol: 28, ReduceChildCount: 2},
		// [117]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: false},
		{Type: ts.ParseActionTypeReduce, ReduceSymbol: 28, ReduceChildCount: 2},
		// [119]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeReduce, ReduceSymbol: 34, ReduceChildCount: 4},
		// [121]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: false},
		{Type: ts.ParseActionTypeReduce, ReduceSymbol: 34, ReduceChildCount: 4},
		// [123]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeReduce, ReduceSymbol: 40, ReduceChildCount: 2},
		// [125]
		{Type: ts.ParseActionTypeHeader, Count: 2, Reusable: true},
		{Type: ts.ParseActionTypeShift, ShiftState: 45, ShiftRepetition: true},
		{Type: ts.ParseActionTypeReduce, ReduceSymbol: 40, ReduceChildCount: 2},
		// [128]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeShift, ShiftState: 18},
		// [130]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeShift, ShiftState: 34},
		// [132]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeShift, ShiftState: 45},
		// [134]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeShift, ShiftState: 11},
		// [136]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeShift, ShiftState: 25},
		// [138]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeShift, ShiftState: 31},
		// [140]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeShift, ShiftState: 12},
		// [142]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeShift, ShiftState: 67},
		// [144]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeShift, ShiftState: 51},
		// [146]
		{Type: ts.ParseActionTypeHeader, Count: 2, Reusable: true},
		{Type: ts.ParseActionTypeShift, ShiftState: 51, ShiftRepetition: true},
		{Type: ts.ParseActionTypeReduce, ReduceSymbol: 40, ReduceChildCount: 2},
		// [149]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeShift, ShiftState: 66},
		// [151]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeShift, ShiftState: 61},
		// [153]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeShift, ShiftState: 65},
		// [155]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeReduce, ReduceSymbol: 37, ReduceChildCount: 1},
		// [157]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeShift, ShiftState: 46},
		// [159]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeShift, ShiftState: 56},
		// [161]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeShift, ShiftState: 72},
		// [163]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeShift, ShiftState: 62},
		// [165]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeShift, ShiftState: 58},
		// [167]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeShift, ShiftState: 73},
		// [169]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeShift, ShiftState: 74},
		// [171]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeShift, ShiftState: 88},
		// [173]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeShift, ShiftState: 71},
		// [175]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeReduce, ReduceSymbol: 38, ReduceChildCount: 2},
		// [177]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeReduce, ReduceSymbol: 38, ReduceChildCount: 3},
		// [179]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeShift, ShiftState: 47},
		// [181]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeShift, ShiftState: 39},
		// [183]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeShift, ShiftState: 43},
		// [185]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeShift, ShiftState: 42},
		// [187]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeShift, ShiftState: 60},
		// [189]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeShift, ShiftState: 92},
		// [191]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeShift, ShiftState: 69},
		// [193]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeShift, ShiftState: 70},
		// [195]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeReduce, ReduceSymbol: 37, ReduceChildCount: 3},
		// [197]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeShift, ShiftState: 37},
		// [199]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeShift, ShiftState: 82},
		// [201]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeShift, ShiftState: 91},
		// [203]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeReduce, ReduceSymbol: 32, ReduceChildCount: 3},
		// [205]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: false},
		{Type: ts.ParseActionTypeShift, ShiftState: 49},
		// [207]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeShift, ShiftState: 76},
		// [209]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeReduce, ReduceSymbol: 32, ReduceChildCount: 4},
		// [211]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeReduce, ReduceSymbol: 33, ReduceChildCount: 3},
		// [213]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeReduce, ReduceSymbol: 33, ReduceChildCount: 4},
		// [215]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeShift, ShiftState: 87},
		// [217]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeShift, ShiftState: 78},
		// [219]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: false},
		{Type: ts.ParseActionTypeShift, ShiftState: 63},
		// [221]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeShift, ShiftState: 86},
		// [223]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeShift, ShiftState: 75},
		// [225]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeShift, ShiftState: 64},
		// [227]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeShift, ShiftState: 50},
		// [229]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeShift, ShiftState: 81},
		// [231]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeShift, ShiftState: 17},
		// [233]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeShift, ShiftState: 30},
		// [235]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeShift, ShiftState: 79},
		// [237]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeShift, ShiftState: 9},
		// [239]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeAccept},
		// [241]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeShift, ShiftState: 13},
		// [243]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeShift, ShiftState: 84},
		// [245]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeShift, ShiftState: 20},
		// [247]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeShift, ShiftState: 80},
		// [249]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeShift, ShiftState: 26},
		// [251]
		{Type: ts.ParseActionTypeHeader, Count: 1, Reusable: true},
		{Type: ts.ParseActionTypeShift, ShiftState: 90},
	}

	parseTable := []uint16{
		// State 0
		1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
		// State 1
		5, 7, 0, 0, 0, 9, 0, 11, 0, 0, 0, 13, 0, 0, 0, 0, 13, 0, 0, 0, 0, 0, 0, 0, 3, 83, 7, 7, 7, 7, 7, 2, 48, 53, 33, 0, 7, 0, 0, 7, 0, 
	}

	smallParseTable := []uint16{
		12, 3, 1, 24, 15, 1, 1, 17, 1, 5, 19, 1, 7, 23, 1, 22, 5, 1, 31, 21, 
		1, 34, 32, 1, 35, 54, 1, 32, 55, 1, 33, 21, 2, 11, 16, 3, 7, 26, 27, 28, 
		29, 30, 36, 39, 12, 3, 1, 24, 15, 1, 1, 17, 1, 5, 19, 1, 7, 27, 1, 22, 
		5, 1, 31, 14, 1, 35, 21, 1, 34, 54, 1, 32, 55, 1, 33, 25, 2, 11, 16, 6, 
		7, 26, 27, 28, 29, 30, 36, 39, 12, 3, 1, 24, 15, 1, 1, 17, 1, 5, 29, 1, 
		7, 31, 1, 22, 5, 1, 31, 21, 1, 34, 27, 1, 35, 54, 1, 32, 55, 1, 33, 25, 
		2, 11, 16, 6, 7, 26, 27, 28, 29, 30, 36, 39, 12, 3, 1, 24, 15, 1, 1, 17, 
		1, 5, 29, 1, 7, 35, 1, 22, 5, 1, 31, 21, 1, 34, 22, 1, 35, 54, 1, 32, 
		55, 1, 33, 33, 2, 11, 16, 4, 7, 26, 27, 28, 29, 30, 36, 39, 11, 3, 1, 24, 
		37, 1, 1, 40, 1, 5, 43, 1, 7, 49, 1, 22, 5, 1, 31, 21, 1, 34, 54, 1, 
		32, 55, 1, 33, 46, 2, 11, 16, 6, 7, 26, 27, 28, 29, 30, 36, 39, 11, 3, 1, 
		24, 7, 1, 1, 9, 1, 5, 11, 1, 7, 51, 1, 0, 2, 1, 31, 33, 1, 34, 48, 
		1, 32, 53, 1, 33, 53, 2, 11, 16, 8, 7, 26, 27, 28, 29, 30, 36, 39, 11, 3, 
		1, 24, 49, 1, 0, 55, 1, 1, 58, 1, 5, 61, 1, 7, 2, 1, 31, 33, 1, 34, 
		48, 1, 32, 53, 1, 33, 64, 2, 11, 16, 8, 7, 26, 27, 28, 29, 30, 36, 39, 3, 
		3, 1, 24, 69, 1, 5, 67, 5, 22, 1, 7, 11, 16, 3, 3, 1, 24, 73, 1, 5, 
		71, 5, 0, 1, 7, 11, 16, 3, 3, 1, 24, 77, 1, 5, 75, 5, 22, 1, 7, 11, 
		16, 3, 3, 1, 24, 81, 1, 5, 79, 5, 0, 1, 7, 11, 16, 3, 3, 1, 24, 85, 
		1, 5, 83, 5, 0, 1, 7, 11, 16, 3, 3, 1, 24, 89, 1, 5, 87, 5, 0, 1, 
		7, 11, 16, 3, 3, 1, 24, 93, 1, 5, 91, 5, 0, 1, 7, 11, 16, 3, 3, 1, 
		24, 97, 1, 5, 95, 5, 0, 1, 7, 11, 16, 3, 3, 1, 24, 101, 1, 5, 99, 5, 
		0, 1, 7, 11, 16, 3, 3, 1, 24, 105, 1, 5, 103, 5, 22, 1, 7, 11, 16, 3, 
		3, 1, 24, 109, 1, 5, 107, 5, 0, 1, 7, 11, 16, 3, 3, 1, 24, 69, 1, 5, 
		67, 5, 0, 1, 7, 11, 16, 3, 3, 1, 24, 113, 1, 5, 111, 5, 22, 1, 7, 11, 
		16, 3, 3, 1, 24, 117, 1, 5, 115, 5, 22, 1, 7, 11, 16, 3, 3, 1, 24, 109, 
		1, 5, 107, 5, 22, 1, 7, 11, 16, 3, 3, 1, 24, 73, 1, 5, 71, 5, 22, 1, 
		7, 11, 16, 3, 3, 1, 24, 81, 1, 5, 79, 5, 22, 1, 7, 11, 16, 3, 3, 1, 
		24, 85, 1, 5, 83, 5, 22, 1, 7, 11, 16, 3, 3, 1, 24, 89, 1, 5, 87, 5, 
		22, 1, 7, 11, 16, 3, 3, 1, 24, 93, 1, 5, 91, 5, 22, 1, 7, 11, 16, 3, 
		3, 1, 24, 97, 1, 5, 95, 5, 22, 1, 7, 11, 16, 3, 3, 1, 24, 101, 1, 5, 
		99, 5, 22, 1, 7, 11, 16, 3, 3, 1, 24, 121, 1, 5, 119, 5, 22, 1, 7, 11, 
		16, 3, 3, 1, 24, 117, 1, 5, 115, 5, 0, 1, 7, 11, 16, 3, 3, 1, 24, 113, 
		1, 5, 111, 5, 0, 1, 7, 11, 16, 3, 3, 1, 24, 121, 1, 5, 119, 5, 0, 1, 
		7, 11, 16, 4, 3, 1, 24, 125, 1, 9, 123, 2, 3, 6, 35, 2, 37, 40, 5, 3, 
		1, 24, 128, 1, 3, 130, 1, 6, 132, 1, 9, 35, 2, 37, 40, 5, 3, 1, 24, 132, 
		1, 9, 134, 1, 3, 136, 1, 6, 38, 2, 37, 40, 5, 3, 1, 24, 128, 1, 3, 132, 
		1, 9, 138, 1, 6, 35, 2, 37, 40, 5, 3, 1, 24, 132, 1, 9, 134, 1, 3, 140, 
		1, 6, 36, 2, 37, 40, 4, 3, 1, 24, 142, 1, 3, 144, 1, 9, 41, 2, 37, 40, 
		4, 3, 1, 24, 123, 1, 3, 146, 1, 9, 41, 2, 37, 40, 4, 3, 1, 24, 144, 1, 
		9, 149, 1, 3, 40, 2, 37, 40, 4, 3, 1, 24, 144, 1, 9, 151, 1, 3, 44, 2, 
		37, 40, 4, 3, 1, 24, 144, 1, 9, 153, 1, 3, 41, 2, 37, 40, 3, 3, 1, 24, 
		157, 1, 8, 155, 3, 3, 6, 9, 5, 3, 1, 24, 159, 1, 10, 161, 1, 12, 163, 1, 
		14, 56, 1, 38, 5, 3, 1, 24, 165, 1, 10, 167, 1, 12, 169, 1, 14, 58, 1, 38, 
		4, 3, 1, 24, 171, 1, 7, 173, 1, 23, 19, 1, 35, 2, 3, 1, 24, 175, 3, 3, 
		6, 9, 2, 3, 1, 24, 177, 3, 3, 6, 9, 3, 3, 1, 24, 179, 1, 8, 155, 2, 
		3, 9, 4, 3, 1, 24, 181, 1, 17, 183, 1, 18, 185, 1, 19, 4, 3, 1, 24, 171, 
		1, 7, 187, 1, 23, 10, 1, 35, 4, 3, 1, 24, 189, 1, 7, 191, 1, 23, 23, 1, 
		35, 4, 3, 1, 24, 189, 1, 7, 193, 1, 23, 24, 1, 35, 2, 3, 1, 24, 195, 3, 
		3, 6, 9, 4, 3, 1, 24, 183, 1, 18, 185, 1, 19, 197, 1, 17, 2, 3, 1, 24, 
		195, 2, 3, 9, 3, 3, 1, 24, 199, 1, 20, 201, 1, 21, 3, 3, 1, 24, 171, 1, 
		7, 16, 1, 35, 2, 3, 1, 24, 203, 2, 23, 7, 3, 3, 1, 24, 205, 1, 14, 207, 
		1, 15, 2, 3, 1, 24, 175, 2, 3, 9, 2, 3, 1, 24, 177, 2, 3, 9, 2, 3, 
		1, 24, 209, 2, 23, 7, 2, 3, 1, 24, 211, 2, 23, 7, 2, 3, 1, 24, 213, 2, 
		23, 7, 3, 3, 1, 24, 201, 1, 21, 215, 1, 20, 3, 3, 1, 24, 189, 1, 7, 28, 
		1, 35, 3, 3, 1, 24, 189, 1, 7, 29, 1, 35, 3, 3, 1, 24, 171, 1, 7, 15, 
		1, 35, 3, 3, 1, 24, 205, 1, 12, 217, 1, 13, 3, 3, 1, 24, 219, 1, 12, 221, 
		1, 13, 3, 3, 1, 24, 219, 1, 14, 223, 1, 15, 2, 3, 1, 24, 225, 1, 14, 2, 
		3, 1, 24, 227, 1, 14, 2, 3, 1, 24, 229, 1, 4, 2, 3, 1, 24, 227, 1, 12, 
		2, 3, 1, 24, 231, 1, 3, 2, 3, 1, 24, 233, 1, 3, 2, 3, 1, 24, 235, 1, 
		2, 2, 3, 1, 24, 237, 1, 3, 2, 3, 1, 24, 239, 1, 0, 2, 3, 1, 24, 241, 
		1, 3, 2, 3, 1, 24, 243, 1, 21, 2, 3, 1, 24, 225, 1, 12, 2, 3, 1, 24, 
		245, 1, 3, 2, 3, 1, 24, 215, 1, 20, 2, 3, 1, 24, 201, 1, 21, 2, 3, 1, 
		24, 247, 1, 2, 2, 3, 1, 24, 249, 1, 3, 2, 3, 1, 24, 199, 1, 20, 2, 3, 
		1, 24, 251, 1, 4, 
	}

	smallParseTableMap := []uint32{
		0, 44, 88, 132, 176, 217, 258, 299, 313, 327, 
		341, 355, 369, 383, 397, 411, 425, 439, 453, 467, 
		481, 495, 509, 523, 537, 551, 565, 579, 593, 607, 
		621, 635, 649, 663, 678, 695, 712, 729, 746, 760, 
		774, 788, 802, 816, 828, 844, 860, 873, 882, 891, 
		902, 915, 928, 941, 954, 963, 976, 984, 994, 1004, 
		1012, 1022, 1030, 1038, 1046, 1054, 1062, 1072, 1082, 1092, 
		1102, 1112, 1122, 1132, 1139, 1146, 1153, 1160, 1167, 1174, 
		1181, 1188, 1195, 1202, 1209, 1216, 1223, 1230, 1237, 1244, 
		1251, 1258, 
	}

	lexModes := []ts.LexMode{
		{LexState: 0, ExternalLexState: 1}, // state 0
		{LexState: 17, ExternalLexState: 2}, // state 1
		{LexState: 17, ExternalLexState: 3}, // state 2
		{LexState: 17, ExternalLexState: 3}, // state 3
		{LexState: 17, ExternalLexState: 3}, // state 4
		{LexState: 17, ExternalLexState: 3}, // state 5
		{LexState: 17, ExternalLexState: 3}, // state 6
		{LexState: 17, ExternalLexState: 2}, // state 7
		{LexState: 17, ExternalLexState: 2}, // state 8
		{LexState: 17, ExternalLexState: 3}, // state 9
		{LexState: 17, ExternalLexState: 2}, // state 10
		{LexState: 17, ExternalLexState: 3}, // state 11
		{LexState: 17, ExternalLexState: 2}, // state 12
		{LexState: 17, ExternalLexState: 2}, // state 13
		{LexState: 17, ExternalLexState: 2}, // state 14
		{LexState: 17, ExternalLexState: 2}, // state 15
		{LexState: 17, ExternalLexState: 2}, // state 16
		{LexState: 17, ExternalLexState: 2}, // state 17
		{LexState: 17, ExternalLexState: 3}, // state 18
		{LexState: 17, ExternalLexState: 2}, // state 19
		{LexState: 17, ExternalLexState: 2}, // state 20
		{LexState: 17, ExternalLexState: 3}, // state 21
		{LexState: 17, ExternalLexState: 3}, // state 22
		{LexState: 17, ExternalLexState: 3}, // state 23
		{LexState: 17, ExternalLexState: 3}, // state 24
		{LexState: 17, ExternalLexState: 3}, // state 25
		{LexState: 17, ExternalLexState: 3}, // state 26
		{LexState: 17, ExternalLexState: 3}, // state 27
		{LexState: 17, ExternalLexState: 3}, // state 28
		{LexState: 17, ExternalLexState: 3}, // state 29
		{LexState: 17, ExternalLexState: 3}, // state 30
		{LexState: 17, ExternalLexState: 3}, // state 31
		{LexState: 17, ExternalLexState: 2}, // state 32
		{LexState: 17, ExternalLexState: 2}, // state 33
		{LexState: 17, ExternalLexState: 2}, // state 34
		{LexState: 5, ExternalLexState: 4}, // state 35
		{LexState: 5, ExternalLexState: 4}, // state 36
		{LexState: 5, ExternalLexState: 4}, // state 37
		{LexState: 5, ExternalLexState: 4}, // state 38
		{LexState: 5, ExternalLexState: 4}, // state 39
		{LexState: 5, ExternalLexState: 2}, // state 40
		{LexState: 5, ExternalLexState: 2}, // state 41
		{LexState: 5, ExternalLexState: 2}, // state 42
		{LexState: 5, ExternalLexState: 2}, // state 43
		{LexState: 5, ExternalLexState: 2}, // state 44
		{LexState: 5, ExternalLexState: 4}, // state 45
		{LexState: 1, ExternalLexState: 2}, // state 46
		{LexState: 1, ExternalLexState: 2}, // state 47
		{LexState: 0, ExternalLexState: 5}, // state 48
		{LexState: 5, ExternalLexState: 4}, // state 49
		{LexState: 5, ExternalLexState: 4}, // state 50
		{LexState: 5, ExternalLexState: 2}, // state 51
		{LexState: 0, ExternalLexState: 6}, // state 52
		{LexState: 0, ExternalLexState: 5}, // state 53
		{LexState: 0, ExternalLexState: 5}, // state 54
		{LexState: 0, ExternalLexState: 5}, // state 55
		{LexState: 5, ExternalLexState: 4}, // state 56
		{LexState: 0, ExternalLexState: 6}, // state 57
		{LexState: 5, ExternalLexState: 2}, // state 58
		{LexState: 0, ExternalLexState: 7}, // state 59
		{LexState: 0, ExternalLexState: 2}, // state 60
		{LexState: 0, ExternalLexState: 5}, // state 61
		{LexState: 2, ExternalLexState: 2}, // state 62
		{LexState: 5, ExternalLexState: 2}, // state 63
		{LexState: 5, ExternalLexState: 2}, // state 64
		{LexState: 0, ExternalLexState: 5}, // state 65
		{LexState: 0, ExternalLexState: 5}, // state 66
		{LexState: 0, ExternalLexState: 5}, // state 67
		{LexState: 0, ExternalLexState: 7}, // state 68
		{LexState: 0, ExternalLexState: 2}, // state 69
		{LexState: 0, ExternalLexState: 2}, // state 70
		{LexState: 0, ExternalLexState: 2}, // state 71
		{LexState: 4, ExternalLexState: 2}, // state 72
		{LexState: 4, ExternalLexState: 2}, // state 73
		{LexState: 2, ExternalLexState: 2}, // state 74
		{LexState: 0, ExternalLexState: 2}, // state 75
		{LexState: 0, ExternalLexState: 2}, // state 76
		{LexState: 0, ExternalLexState: 2}, // state 77
		{LexState: 0, ExternalLexState: 2}, // state 78
		{LexState: 0, ExternalLexState: 2}, // state 79
		{LexState: 0, ExternalLexState: 2}, // state 80
		{LexState: 15, ExternalLexState: 2}, // state 81
		{LexState: 0, ExternalLexState: 2}, // state 82
		{LexState: 0, ExternalLexState: 2}, // state 83
		{LexState: 0, ExternalLexState: 2}, // state 84
		{LexState: 0, ExternalLexState: 8}, // state 85
		{LexState: 0, ExternalLexState: 2}, // state 86
		{LexState: 0, ExternalLexState: 2}, // state 87
		{LexState: 0, ExternalLexState: 9}, // state 88
		{LexState: 0, ExternalLexState: 8}, // state 89
		{LexState: 15, ExternalLexState: 2}, // state 90
		{LexState: 0, ExternalLexState: 2}, // state 91
		{LexState: 0, ExternalLexState: 9}, // state 92
		{LexState: 0, ExternalLexState: 2}, // state 93
	}

	primaryStateIDs := []ts.StateID{
		0, 1, 2, 3, 3, 2, 6, 7, 6, 9, 
		10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 
		9, 21, 22, 19, 10, 12, 13, 14, 15, 16, 
		17, 31, 22, 21, 31, 35, 36, 37, 36, 37, 
		40, 35, 42, 43, 44, 45, 46, 46, 48, 49, 
		50, 45, 52, 53, 48, 53, 56, 52, 56, 59, 
		60, 61, 62, 49, 50, 65, 66, 67, 59, 69, 
		60, 69, 72, 72, 62, 75, 75, 77, 78, 79, 
		79, 81, 82, 83, 84, 85, 78, 82, 88, 85, 
		81, 84, 88, 77, 
	}

	aliasSequences := make([]ts.Symbol, 4)
	_ = aliasSequences

	symbolMetadata := []ts.SymbolMetadata{
		{Visible: false, Named: true}, // 0: end
		{Visible: true, Named: false}, // 1: <!
		{Visible: false, Named: false}, // 2: doctype_token1
		{Visible: true, Named: false}, // 3: >
		{Visible: true, Named: false}, // 4: doctype
		{Visible: true, Named: false}, // 5: <
		{Visible: true, Named: false}, // 6: />
		{Visible: true, Named: false}, // 7: </
		{Visible: true, Named: false}, // 8: =
		{Visible: true, Named: true}, // 9: attribute_name
		{Visible: true, Named: true}, // 10: attribute_value
		{Visible: true, Named: true}, // 11: entity
		{Visible: true, Named: false}, // 12: '
		{Visible: true, Named: true}, // 13: attribute_value
		{Visible: true, Named: false}, // 14: "
		{Visible: true, Named: true}, // 15: attribute_value
		{Visible: true, Named: true}, // 16: text
		{Visible: true, Named: true}, // 17: tag_name
		{Visible: true, Named: true}, // 18: tag_name
		{Visible: true, Named: true}, // 19: tag_name
		{Visible: true, Named: true}, // 20: tag_name
		{Visible: true, Named: true}, // 21: erroneous_end_tag_name
		{Visible: false, Named: true}, // 22: _implicit_end_tag
		{Visible: true, Named: true}, // 23: raw_text
		{Visible: true, Named: true}, // 24: comment
		{Visible: true, Named: true}, // 25: document
		{Visible: true, Named: true}, // 26: doctype
		{Visible: false, Named: true}, // 27: _node
		{Visible: true, Named: true}, // 28: element
		{Visible: true, Named: true}, // 29: script_element
		{Visible: true, Named: true}, // 30: style_element
		{Visible: true, Named: true}, // 31: start_tag
		{Visible: true, Named: true}, // 32: start_tag
		{Visible: true, Named: true}, // 33: start_tag
		{Visible: true, Named: true}, // 34: self_closing_tag
		{Visible: true, Named: true}, // 35: end_tag
		{Visible: true, Named: true}, // 36: erroneous_end_tag
		{Visible: true, Named: true}, // 37: attribute
		{Visible: true, Named: true}, // 38: quoted_attribute_value
		{Visible: false, Named: false}, // 39: document_repeat1
		{Visible: false, Named: false}, // 40: start_tag_repeat1
	}

	symbolNames := []string{
		"end", // 0
		"<!", // 1
		"doctype_token1", // 2
		">", // 3
		"doctype", // 4
		"<", // 5
		"/>", // 6
		"</", // 7
		"=", // 8
		"attribute_name", // 9
		"attribute_value", // 10
		"entity", // 11
		"'", // 12
		"attribute_value", // 13
		"\"", // 14
		"attribute_value", // 15
		"text", // 16
		"tag_name", // 17
		"tag_name", // 18
		"tag_name", // 19
		"tag_name", // 20
		"erroneous_end_tag_name", // 21
		"_implicit_end_tag", // 22
		"raw_text", // 23
		"comment", // 24
		"document", // 25
		"doctype", // 26
		"_node", // 27
		"element", // 28
		"script_element", // 29
		"style_element", // 30
		"start_tag", // 31
		"start_tag", // 32
		"start_tag", // 33
		"self_closing_tag", // 34
		"end_tag", // 35
		"erroneous_end_tag", // 36
		"attribute", // 37
		"quoted_attribute_value", // 38
		"document_repeat1", // 39
		"start_tag_repeat1", // 40
	}

	externalScannerStates := []bool{
		false, false, false, false, false, false, false, false, false, true, true, true, true, true, true, true, true, true, false, false, 
		false, false, false, false, false, false, true, false, false, false, false, false, false, true, false, true, false, false, false, false, 
		false, true, false, false, true, false, false, false, false, false, false, false, true, true, true, true, true, false, false, false, 
		false, false, true, false, false, false, true, true, false, false, false, true, false, false, false, false, true, false, false, false, 
		true, false, false, false, true, false, false, false, false, true, 
	}

	externalSymbolMap := []ts.Symbol{17, 18, 19, 20, 21, 6, 22, 23, 24, }

	return &ts.Language{
		Version:                14,
		SymbolCount:            41,
		AliasCount:             0,
		TokenCount:             25,
		ExternalTokenCount:     9,
		StateCount:             94,
		LargeStateCount:        2,
		ProductionIDCount:      1,
		FieldCount:             0,
		MaxAliasSequenceLength: 4,
		PrimaryStateIDs:        primaryStateIDs,
		ParseTable:             parseTable,
		SmallParseTable:        smallParseTable,
		SmallParseTableMap:     smallParseTableMap,
		ParseActions:           parseActions,
		LexModes:               lexModes,
		LexFn:                  tsLex,
		SymbolNames:            symbolNames,
		SymbolMetadata:          symbolMetadata,
		AliasSequences:         aliasSequences,
		ExternalScannerStates:  externalScannerStates,
		ExternalSymbolMap:      externalSymbolMap,
	}
}

func tsLex(lexer *ts.Lexer, state ts.StateID) bool {
	result := false
	lookahead := lexer.Lookahead
	eof := lexer.EOF()
	_ = eof

	for {
		switch state {
		case 0:
			if eof {
				state = 18
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead == '"' {
				state = 73
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead == '&' {
				state = 3
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead == '\'' {
				state = 70
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead == '/' {
				state = 6
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead == '<' {
				state = 24
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead == '=' {
				state = 27
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead == '>' {
				state = 22
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead == 'D' {
				state = 9
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead == 'd' {
				state = 9
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= '\t' && lookahead <= '\r' {
				state = 0
				lexer.Advance(true)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead == ' ' {
				state = 0
				lexer.Advance(true)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 1:
			if lookahead == '"' {
				state = 73
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead == '\'' {
				state = 70
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= '\t' && lookahead <= '\r' {
				state = 1
				lexer.Advance(true)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead == ' ' {
				state = 1
				lexer.Advance(true)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if !eof {
				state = 29
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 2:
			if lookahead == '"' {
				state = 73
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= '\t' && lookahead <= '\r' {
				state = 74
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead == ' ' {
				state = 74
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if !eof {
				state = 75
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 3:
			if lookahead == '#' {
				state = 12
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= 'A' && lookahead <= 'Z' {
				state = 69
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= 'a' && lookahead <= 'z' {
				state = 69
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 4:
			if lookahead == '\'' {
				state = 70
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= '\t' && lookahead <= '\r' {
				state = 71
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead == ' ' {
				state = 71
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if !eof {
				state = 72
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 5:
			if lookahead == '/' {
				state = 6
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead == '=' {
				state = 27
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead == '>' {
				state = 22
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= '\t' && lookahead <= '\r' {
				state = 5
				lexer.Advance(true)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead == ' ' {
				state = 5
				lexer.Advance(true)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if !eof && lookahead != '"' && lookahead != '\'' && (lookahead < '<' || lookahead > '>') {
				state = 28
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 6:
			if lookahead == '>' {
				state = 25
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 7:
			if lookahead == 'C' {
				state = 11
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead == 'c' {
				state = 11
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 8:
			if lookahead == 'E' {
				state = 23
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead == 'e' {
				state = 23
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 9:
			if lookahead == 'O' {
				state = 7
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead == 'o' {
				state = 7
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 10:
			if lookahead == 'P' {
				state = 8
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead == 'p' {
				state = 8
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 11:
			if lookahead == 'T' {
				state = 13
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead == 't' {
				state = 13
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 12:
			if lookahead == 'X' {
				state = 16
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead == 'x' {
				state = 16
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= '0' && lookahead <= '9' {
				state = 35
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 13:
			if lookahead == 'Y' {
				state = 10
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead == 'y' {
				state = 10
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 14:
			if lookahead >= '\t' && lookahead <= '\r' {
				state = 14
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead == ' ' {
				state = 14
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if !eof && lookahead != '&' && lookahead != '<' && lookahead != '>' {
				state = 76
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 15:
			if lookahead >= '\t' && lookahead <= '\r' {
				state = 20
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead == ' ' {
				state = 20
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if !eof && lookahead != '>' {
				state = 21
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 16:
			if lookahead >= '0' && lookahead <= '9' {
				state = 40
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= 'A' && lookahead <= 'F' {
				state = 40
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= 'a' && lookahead <= 'f' {
				state = 40
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 17:
			if eof {
				state = 18
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead == '&' {
				state = 3
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead == '<' {
				state = 24
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= '\t' && lookahead <= '\r' {
				state = 17
				lexer.Advance(true)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead == ' ' {
				state = 17
				lexer.Advance(true)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if !eof && lookahead != '>' {
				state = 76
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 18:
			return result
		case 19:
			lexer.MarkEnd()
			lexer.AcceptToken(1)
			result = true
			return result
		case 20:
			lexer.MarkEnd()
			lexer.AcceptToken(2)
			result = true
			if lookahead >= '\t' && lookahead <= '\r' {
				state = 20
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead == ' ' {
				state = 20
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if !eof && lookahead != '>' {
				state = 21
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 21:
			lexer.MarkEnd()
			lexer.AcceptToken(2)
			result = true
			if !eof && lookahead != '>' {
				state = 21
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 22:
			lexer.MarkEnd()
			lexer.AcceptToken(3)
			result = true
			return result
		case 23:
			lexer.MarkEnd()
			lexer.AcceptToken(4)
			result = true
			return result
		case 24:
			lexer.MarkEnd()
			lexer.AcceptToken(5)
			result = true
			if lookahead == '!' {
				state = 19
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead == '/' {
				state = 26
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 25:
			lexer.MarkEnd()
			lexer.AcceptToken(6)
			result = true
			return result
		case 26:
			lexer.MarkEnd()
			lexer.AcceptToken(7)
			result = true
			return result
		case 27:
			lexer.MarkEnd()
			lexer.AcceptToken(8)
			result = true
			return result
		case 28:
			lexer.MarkEnd()
			lexer.AcceptToken(9)
			result = true
			if !eof && lookahead != ' ' && lookahead != '"' && lookahead != '\'' && lookahead != '/' && (lookahead < '\t' || lookahead > '\r') && (lookahead < '<' || lookahead > '>') {
				state = 28
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 29:
			lexer.MarkEnd()
			lexer.AcceptToken(10)
			result = true
			if !eof && lookahead != ' ' && lookahead != '"' && lookahead != '\'' && (lookahead < '\t' || lookahead > '\r') && (lookahead < '<' || lookahead > '>') {
				state = 29
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 30:
			lexer.MarkEnd()
			lexer.AcceptToken(11)
			result = true
			return result
		case 31:
			lexer.MarkEnd()
			lexer.AcceptToken(11)
			result = true
			if lookahead == ';' {
				state = 30
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 32:
			lexer.MarkEnd()
			lexer.AcceptToken(11)
			result = true
			if lookahead == ';' {
				state = 30
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= '0' && lookahead <= '9' {
				state = 31
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 33:
			lexer.MarkEnd()
			lexer.AcceptToken(11)
			result = true
			if lookahead == ';' {
				state = 30
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= '0' && lookahead <= '9' {
				state = 32
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 34:
			lexer.MarkEnd()
			lexer.AcceptToken(11)
			result = true
			if lookahead == ';' {
				state = 30
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= '0' && lookahead <= '9' {
				state = 33
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 35:
			lexer.MarkEnd()
			lexer.AcceptToken(11)
			result = true
			if lookahead == ';' {
				state = 30
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= '0' && lookahead <= '9' {
				state = 34
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 36:
			lexer.MarkEnd()
			lexer.AcceptToken(11)
			result = true
			if lookahead == ';' {
				state = 30
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= '0' && lookahead <= '9' {
				state = 31
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= 'A' && lookahead <= 'F' {
				state = 31
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= 'a' && lookahead <= 'f' {
				state = 31
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 37:
			lexer.MarkEnd()
			lexer.AcceptToken(11)
			result = true
			if lookahead == ';' {
				state = 30
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= '0' && lookahead <= '9' {
				state = 36
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= 'A' && lookahead <= 'F' {
				state = 36
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= 'a' && lookahead <= 'f' {
				state = 36
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 38:
			lexer.MarkEnd()
			lexer.AcceptToken(11)
			result = true
			if lookahead == ';' {
				state = 30
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= '0' && lookahead <= '9' {
				state = 37
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= 'A' && lookahead <= 'F' {
				state = 37
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= 'a' && lookahead <= 'f' {
				state = 37
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 39:
			lexer.MarkEnd()
			lexer.AcceptToken(11)
			result = true
			if lookahead == ';' {
				state = 30
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= '0' && lookahead <= '9' {
				state = 38
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= 'A' && lookahead <= 'F' {
				state = 38
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= 'a' && lookahead <= 'f' {
				state = 38
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 40:
			lexer.MarkEnd()
			lexer.AcceptToken(11)
			result = true
			if lookahead == ';' {
				state = 30
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= '0' && lookahead <= '9' {
				state = 39
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= 'A' && lookahead <= 'F' {
				state = 39
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= 'a' && lookahead <= 'f' {
				state = 39
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 41:
			lexer.MarkEnd()
			lexer.AcceptToken(11)
			result = true
			if lookahead == ';' {
				state = 30
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= 'A' && lookahead <= 'Z' {
				state = 31
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= 'a' && lookahead <= 'z' {
				state = 31
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 42:
			lexer.MarkEnd()
			lexer.AcceptToken(11)
			result = true
			if lookahead == ';' {
				state = 30
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= 'A' && lookahead <= 'Z' {
				state = 41
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= 'a' && lookahead <= 'z' {
				state = 41
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 43:
			lexer.MarkEnd()
			lexer.AcceptToken(11)
			result = true
			if lookahead == ';' {
				state = 30
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= 'A' && lookahead <= 'Z' {
				state = 42
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= 'a' && lookahead <= 'z' {
				state = 42
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 44:
			lexer.MarkEnd()
			lexer.AcceptToken(11)
			result = true
			if lookahead == ';' {
				state = 30
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= 'A' && lookahead <= 'Z' {
				state = 43
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= 'a' && lookahead <= 'z' {
				state = 43
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 45:
			lexer.MarkEnd()
			lexer.AcceptToken(11)
			result = true
			if lookahead == ';' {
				state = 30
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= 'A' && lookahead <= 'Z' {
				state = 44
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= 'a' && lookahead <= 'z' {
				state = 44
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 46:
			lexer.MarkEnd()
			lexer.AcceptToken(11)
			result = true
			if lookahead == ';' {
				state = 30
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= 'A' && lookahead <= 'Z' {
				state = 45
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= 'a' && lookahead <= 'z' {
				state = 45
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 47:
			lexer.MarkEnd()
			lexer.AcceptToken(11)
			result = true
			if lookahead == ';' {
				state = 30
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= 'A' && lookahead <= 'Z' {
				state = 46
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= 'a' && lookahead <= 'z' {
				state = 46
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 48:
			lexer.MarkEnd()
			lexer.AcceptToken(11)
			result = true
			if lookahead == ';' {
				state = 30
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= 'A' && lookahead <= 'Z' {
				state = 47
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= 'a' && lookahead <= 'z' {
				state = 47
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 49:
			lexer.MarkEnd()
			lexer.AcceptToken(11)
			result = true
			if lookahead == ';' {
				state = 30
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= 'A' && lookahead <= 'Z' {
				state = 48
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= 'a' && lookahead <= 'z' {
				state = 48
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 50:
			lexer.MarkEnd()
			lexer.AcceptToken(11)
			result = true
			if lookahead == ';' {
				state = 30
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= 'A' && lookahead <= 'Z' {
				state = 49
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= 'a' && lookahead <= 'z' {
				state = 49
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 51:
			lexer.MarkEnd()
			lexer.AcceptToken(11)
			result = true
			if lookahead == ';' {
				state = 30
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= 'A' && lookahead <= 'Z' {
				state = 50
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= 'a' && lookahead <= 'z' {
				state = 50
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 52:
			lexer.MarkEnd()
			lexer.AcceptToken(11)
			result = true
			if lookahead == ';' {
				state = 30
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= 'A' && lookahead <= 'Z' {
				state = 51
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= 'a' && lookahead <= 'z' {
				state = 51
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 53:
			lexer.MarkEnd()
			lexer.AcceptToken(11)
			result = true
			if lookahead == ';' {
				state = 30
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= 'A' && lookahead <= 'Z' {
				state = 52
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= 'a' && lookahead <= 'z' {
				state = 52
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 54:
			lexer.MarkEnd()
			lexer.AcceptToken(11)
			result = true
			if lookahead == ';' {
				state = 30
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= 'A' && lookahead <= 'Z' {
				state = 53
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= 'a' && lookahead <= 'z' {
				state = 53
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 55:
			lexer.MarkEnd()
			lexer.AcceptToken(11)
			result = true
			if lookahead == ';' {
				state = 30
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= 'A' && lookahead <= 'Z' {
				state = 54
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= 'a' && lookahead <= 'z' {
				state = 54
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 56:
			lexer.MarkEnd()
			lexer.AcceptToken(11)
			result = true
			if lookahead == ';' {
				state = 30
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= 'A' && lookahead <= 'Z' {
				state = 55
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= 'a' && lookahead <= 'z' {
				state = 55
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 57:
			lexer.MarkEnd()
			lexer.AcceptToken(11)
			result = true
			if lookahead == ';' {
				state = 30
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= 'A' && lookahead <= 'Z' {
				state = 56
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= 'a' && lookahead <= 'z' {
				state = 56
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 58:
			lexer.MarkEnd()
			lexer.AcceptToken(11)
			result = true
			if lookahead == ';' {
				state = 30
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= 'A' && lookahead <= 'Z' {
				state = 57
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= 'a' && lookahead <= 'z' {
				state = 57
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 59:
			lexer.MarkEnd()
			lexer.AcceptToken(11)
			result = true
			if lookahead == ';' {
				state = 30
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= 'A' && lookahead <= 'Z' {
				state = 58
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= 'a' && lookahead <= 'z' {
				state = 58
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 60:
			lexer.MarkEnd()
			lexer.AcceptToken(11)
			result = true
			if lookahead == ';' {
				state = 30
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= 'A' && lookahead <= 'Z' {
				state = 59
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= 'a' && lookahead <= 'z' {
				state = 59
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 61:
			lexer.MarkEnd()
			lexer.AcceptToken(11)
			result = true
			if lookahead == ';' {
				state = 30
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= 'A' && lookahead <= 'Z' {
				state = 60
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= 'a' && lookahead <= 'z' {
				state = 60
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 62:
			lexer.MarkEnd()
			lexer.AcceptToken(11)
			result = true
			if lookahead == ';' {
				state = 30
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= 'A' && lookahead <= 'Z' {
				state = 61
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= 'a' && lookahead <= 'z' {
				state = 61
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 63:
			lexer.MarkEnd()
			lexer.AcceptToken(11)
			result = true
			if lookahead == ';' {
				state = 30
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= 'A' && lookahead <= 'Z' {
				state = 62
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= 'a' && lookahead <= 'z' {
				state = 62
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 64:
			lexer.MarkEnd()
			lexer.AcceptToken(11)
			result = true
			if lookahead == ';' {
				state = 30
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= 'A' && lookahead <= 'Z' {
				state = 63
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= 'a' && lookahead <= 'z' {
				state = 63
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 65:
			lexer.MarkEnd()
			lexer.AcceptToken(11)
			result = true
			if lookahead == ';' {
				state = 30
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= 'A' && lookahead <= 'Z' {
				state = 64
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= 'a' && lookahead <= 'z' {
				state = 64
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 66:
			lexer.MarkEnd()
			lexer.AcceptToken(11)
			result = true
			if lookahead == ';' {
				state = 30
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= 'A' && lookahead <= 'Z' {
				state = 65
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= 'a' && lookahead <= 'z' {
				state = 65
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 67:
			lexer.MarkEnd()
			lexer.AcceptToken(11)
			result = true
			if lookahead == ';' {
				state = 30
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= 'A' && lookahead <= 'Z' {
				state = 66
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= 'a' && lookahead <= 'z' {
				state = 66
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 68:
			lexer.MarkEnd()
			lexer.AcceptToken(11)
			result = true
			if lookahead == ';' {
				state = 30
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= 'A' && lookahead <= 'Z' {
				state = 67
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= 'a' && lookahead <= 'z' {
				state = 67
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 69:
			lexer.MarkEnd()
			lexer.AcceptToken(11)
			result = true
			if lookahead == ';' {
				state = 30
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= 'A' && lookahead <= 'Z' {
				state = 68
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead >= 'a' && lookahead <= 'z' {
				state = 68
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 70:
			lexer.MarkEnd()
			lexer.AcceptToken(12)
			result = true
			return result
		case 71:
			lexer.MarkEnd()
			lexer.AcceptToken(13)
			result = true
			if lookahead >= '\t' && lookahead <= '\r' {
				state = 71
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead == ' ' {
				state = 71
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if !eof && lookahead != '\'' {
				state = 72
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 72:
			lexer.MarkEnd()
			lexer.AcceptToken(13)
			result = true
			if !eof && lookahead != '\'' {
				state = 72
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 73:
			lexer.MarkEnd()
			lexer.AcceptToken(14)
			result = true
			return result
		case 74:
			lexer.MarkEnd()
			lexer.AcceptToken(15)
			result = true
			if lookahead >= '\t' && lookahead <= '\r' {
				state = 74
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead == ' ' {
				state = 74
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if !eof && lookahead != '"' {
				state = 75
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 75:
			lexer.MarkEnd()
			lexer.AcceptToken(15)
			result = true
			if !eof && lookahead != '"' {
				state = 75
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		case 76:
			lexer.MarkEnd()
			lexer.AcceptToken(16)
			result = true
			if lookahead >= '\t' && lookahead <= '\r' {
				state = 14
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if lookahead == ' ' {
				state = 14
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			if !eof && lookahead != '&' && lookahead != '<' && lookahead != '>' {
				state = 76
				lexer.Advance(false)
				lookahead = lexer.Lookahead
				eof = lexer.EOF()
				continue
			}
			return result
		default:
			return false
		}
	}
}

